// One-command deterministic G6 cook: K1 events + streamed terrain + R2 art.
// Usage: TUXEMON_SRC=/path/to/Tuxemon bun gen-assets.ts

import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { cookAnimationAtlases } from "./vendor/pocket-rpgkit/tools/lib/animated.ts";
import { splitProjectMaps } from "./vendor/pocket-rpgkit/tools/lib/map-project.ts";
import { pakManifest, type PakManifestEntry } from "./vendor/pocket-rpgkit/tools/lib/stream.ts";
import { assertShellManifestFresh } from "./vendor/pocket-rpgkit/src/engine/map-repository.ts";
import type { GameAssets } from "./vendor/pocket-rpgkit/src/ui/game-assets.ts";
import type { PlayerFrames } from "./vendor/pocket-rpgkit/src/ui/PlayerSprite.tsx";
import type { Project } from "./vendor/pocket-rpgkit/src/engine/types.ts";
import { splitAnimatedTiles, type AnimatedIndexEntry } from "./importer/animated.ts";
import { collectNpcSrcAssetPaths, splitNpcSrc, type NpcSrcIndexEntry } from "./importer/npc-src.ts";
import { cookCharacters } from "./importer/characters.ts";
import { appendBattleDbPakEntry, writeBattleArtifacts } from "./importer/battle.ts";
import { coverageMarkdown, jsonBytes } from "./importer/index.ts";
import { availableMapIds, buildProject, G6_IMPORT_OPTIONS } from "./importer/project.ts";
import { applyTerrain, writeTerrain } from "./importer/terrain.ts";

// Tests and determinism checks can cook into a disposable root without
// touching the maintained project tree. Source modules still come from this
// checkout; only generated outputs are redirected.
const ROOT = resolve(process.env.G6_OUTPUT_ROOT ?? import.meta.dir);
const DIST = join(ROOT, "dist");
mkdirSync(DIST, { recursive: true });
mkdirSync(join(ROOT, "findings"), { recursive: true });

const terrain = writeTerrain({ outputRoot: ROOT });
const imported = buildProject(availableMapIds(), G6_IMPORT_OPTIONS);
let project = applyTerrain(imported.project, terrain.fragment);
// The G1 one-tile sheet is now unused: every ground id and passage mask is
// owned by the generated terrain sheet.
project = {
  ...project,
  sheets: project.sheets.filter((sheet) => sheet.id !== "tux"),
  maps: project.maps.map((map) => ({ ...map, sheets: map.sheets?.filter((sheet) => sheet !== "tux") })),
};

const characters = await cookCharacters(project, { outputRoot: ROOT });
project = characters.project;
const battleScope = process.env.BATTLE_DB_SCOPE === "full" ? "full" : "spyder";
const battle = writeBattleArtifacts({ outputRoot: ROOT, scope: battleScope });

// GP1: GameAssets.npcSrc used to bundle every NPC's sprite-frame paths as
// one eager literal. Split it the same way animated tiles are split — one
// canonical entry per NPC art id — so ui/npc-src-repository.ts can
// resolve+cache only the NPCs a session actually spawns.
const npcSrcSplit = splitNpcSrc(characters.npcSrc);
const npcSrcDir = join(DIST, "npc-src");
rmSync(npcSrcDir, { recursive: true, force: true });
mkdirSync(npcSrcDir, { recursive: true });
for (const entry of npcSrcSplit.entries) {
  const path = join(DIST, entry.path);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, entry.bytes);
}
const npcSrcPakEntries: PakManifestEntry[] = npcSrcSplit.entries.map((entry) => ({
  key: entry.meta.entry,
  file: `dist/${entry.path}`,
}));
// PocketJS bakes an "assets/..." image into the pak only when its literal
// path string is reachable from scanned TS/TSX source (this is how
// ui/battle-assets.ts's BATTLE_ASSET_PATHS already works for battle
// textures). Moving NPC_SRC into JSON shards hid these paths from that
// scanner, so this keeps them reachable the same way.
const npcSrcAssetPaths = [...new Set(Object.values(characters.npcSrc).flatMap(collectNpcSrcAssetPaths))].sort();
writeFileSync(
  join(ROOT, "ui/npc-src-assets.ts"),
  "// AUTO-GENERATED by gen-assets.ts — do not edit.\n" +
  "// Keeping these literal paths reachable makes PocketJS bake every NPC sprite texture into the app pak.\n" +
  `export const NPC_SRC_ASSET_PATHS = ${JSON.stringify(npcSrcAssetPaths, null, 2)} as const;\n`,
);

// GameView cannot scan unloaded MapDefs, so sharded projects bake the one
// all-map rendering scalar it needs into the asset manifest.
const sprites = project.sprites ?? {};
const maxActors = Math.max(0, ...project.maps.map((map) =>
  (map.events ?? []).filter((event) => event.pages.some((page) => {
    const sprite = page.sprite == null ? undefined : sprites[page.sprite];
    return !!sprite && (sprite.kind === "walker" || !!sprite.src);
  })).length));

// Animated tile atlases are globally shared by equal RGBA sequences.
const animDir = join(ROOT, "assets/anim");
rmSync(animDir, { recursive: true, force: true });
mkdirSync(animDir, { recursive: true });
const cooked = cookAnimationAtlases(terrain.animationSequences, {
  directory: "assets/anim",
  prefix: "terrain",
});
for (const atlas of cooked.atlases) {
  const path = join(ROOT, atlas.file);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, atlas.png);
}
const animatedMaps = Object.entries(terrain.animations).map(([id, cells]) => ({
  id,
  tiles: cells.map((cell) => {
    const sprite = cooked.atlasFor.get(cell.sequence);
    if (!sprite) throw new Error(`gen-assets: no atlas for ${cell.sequence}`);
    return { x: cell.x, y: cell.y, above: cell.above, sprite };
  }),
}));

// GP1: GameAssets.animated used to bundle every map's placements as one
// eager literal (the largest single input in the desktop bundle). Split it
// the same way battle species/techniques are split — one canonical entry
// per map id — so ui/animated-repository.ts can resolve+cache only the
// maps a session actually visits.
const animatedSplit = splitAnimatedTiles(animatedMaps);
const animatedDir = join(DIST, "animated");
rmSync(animatedDir, { recursive: true, force: true });
mkdirSync(animatedDir, { recursive: true });
for (const entry of animatedSplit.entries) {
  const path = join(DIST, entry.path);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, entry.bytes);
}
const animatedPakEntries: PakManifestEntry[] = animatedSplit.entries.map((entry) => ({
  key: entry.meta.entry,
  file: `dist/${entry.path}`,
}));
// Same reachability requirement as npcSrcAssetPaths below: PocketJS bakes a
// sprites.json-registered atlas only when its literal name string is
// scanned from source. These names used to live inside ANIMATED's inline
// literal; keep them reachable now that they live in dist/animated shards.
const animatedAtlasNames = [...new Set(cooked.atlases.map((atlas) => atlas.name))].sort();
writeFileSync(
  join(ROOT, "ui/animated-assets.ts"),
  "// AUTO-GENERATED by gen-assets.ts — do not edit.\n" +
  "// Keeping these literal names reachable makes PocketJS bake every animated-tile atlas into the app pak.\n" +
  `export const ANIMATED_ATLAS_NAMES = ${JSON.stringify(animatedAtlasNames, null, 2)} as const;\n`,
);

// Keep the inline document as an out-of-bundle parity oracle, while the game
// imports only the compact shell. Each canonical ASCII map payload is a raw
// pak entry addressed by the exact path carried in shell.mapIndex.
const split = splitProjectMaps(project, { shellEntry: "project-shell.json" });
const mapsDir = join(DIST, "maps");
rmSync(mapsDir, { recursive: true, force: true });
mkdirSync(mapsDir, { recursive: true });
for (const entry of split.entries) {
  const path = join(DIST, entry.path);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, entry.bytes);
}

const mapPakEntries: PakManifestEntry[] = split.entries.map((entry) => ({
  key: entry.meta.entry,
  file: `dist/${entry.path}`,
}));
const pakEntries = [
  ...pakManifest(terrain.entries),
  ...mapPakEntries,
  ...battle.battleRepository.pakEntries,
  ...animatedPakEntries,
  ...npcSrcPakEntries,
  ...terrain.streamPakEntries,
].sort((a, b) => a.key < b.key ? -1 : a.key > b.key ? 1 : 0);

writeFileSync(join(ROOT, "sprites.json"), jsonBytes(cooked.spritesJson));
const allImages = { ...characters.imagesJson, ...battle.imagesJson };
writeFileSync(join(ROOT, "images.json"), jsonBytes(allImages));
const allPakEntries = appendBattleDbPakEntry(pakEntries)
  .sort((a, b) => a.key < b.key ? -1 : a.key > b.key ? 1 : 0);
writeFileSync(join(ROOT, "pak.json"), JSON.stringify(allPakEntries, null, 2) + "\n");
writeFileSync(join(DIST, "project.json"), jsonBytes(project));
writeFileSync(join(DIST, "project-shell.json"), split.shellText);
// The runtime trusts the shell's declared mapManifestHash (it no longer
// rehashes at startup), so the packager must prove the bytes on disk are
// fresh: read the shell back and verify the declaration against a recompute.
assertShellManifestFresh(JSON.parse(readFileSync(join(DIST, "project-shell.json"), "utf8")));
writeFileSync(join(DIST, "variable-enums.json"), jsonBytes(imported.variables));
writeFileSync(join(DIST, "import-report.json"), jsonBytes(imported.report));
writeFileSync(join(ROOT, "findings/G1-coverage.md"), coverageMarkdown(imported.report));

function gameAssetsSource(
  player: PlayerFrames,
  maxActors: number,
  animatedIndex: readonly AnimatedIndexEntry[],
  npcSrcIndex: readonly NpcSrcIndexEntry[],
): string {
  return (
    "// AUTO-GENERATED by gen-assets.ts — do not edit.\n" +
    'import type { GameAssets } from "../vendor/pocket-rpgkit/src/ui/game-assets.ts";\n' +
    'import type { PlayerFrames } from "../vendor/pocket-rpgkit/src/ui/PlayerSprite.tsx";\n' +
    'import { TERRAIN_ORDER, TERRAIN_WORLD } from "./terrain-assets.ts";\n\n' +
    `export const PLAYER: PlayerFrames = ${JSON.stringify(player, null, 2)};\n\n` +
    // GP1: the full animated-tile table (48 maps, 5,785 placements) and the
    // full per-NPC sprite-frame table (175 NPCs) are no longer inline
    // literals — together they were the two largest inputs in the desktop
    // bundle this task found. Their INDEX tables (id -> pak/data.fs entry)
    // stay inline because they are tiny; main.tsx builds the lazy Proxies
    // from them via ui/animated-repository.ts and ui/npc-src-repository.ts.
    `export const ANIMATED_INDEX: readonly { id: string; entry: string }[] = ${JSON.stringify(animatedIndex, null, 2)} as const;\n\n` +
    `export const NPC_SRC_INDEX: readonly { id: string; entry: string }[] = ${JSON.stringify(npcSrcIndex, null, 2)} as const;\n\n` +
    "export const GAME_ASSETS: Omit<GameAssets, \"npcSrc\" | \"animated\" | \"stream\"> = {\n" +
    "  ground: {},\n" +
    "  upper: {},\n" +
    "  chunkColumns: {},\n" +
    "  maxChunks: 1,\n" +
    `  maxActors: ${maxActors},\n` +
    "  world: TERRAIN_WORLD,\n" +
    "  order: TERRAIN_ORDER,\n" +
    "  player: PLAYER,\n" +
    "  playerHeight: 32,\n" +
    "};\n"
  );
}

writeFileSync(
  join(ROOT, "ui/game-assets.ts"),
  gameAssetsSource(characters.player, maxActors, animatedSplit.index, npcSrcSplit.index),
);

const collisionBodies = project.maps.reduce(
  (sum, map) => sum + (map.events ?? []).filter((event) => event.name?.startsWith("collision:")).length,
  0,
);
const assetReport = {
  format: "pocket-tuxemon/g6-assets/v1",
  sourceRevision: terrain.report.sourceRevision,
  project: {
    maps: project.maps.length,
    collisionBodies,
    maxActors,
    options: G6_IMPORT_OPTIONS,
  },
  mapRepository: {
    shellBytes: split.files[0]!.bytes.byteLength,
    entryBytes: split.entries.reduce((sum, entry) => sum + entry.bytes.byteLength, 0),
    entries: split.entries.length,
    manifestHash: split.shell.mapManifestHash,
    schemaHash: split.shell.mapSchemaHash,
  },
  terrain: {
    entries: terrain.report.entries,
    pakBytes: terrain.report.pakBytes,
    gzipBytes: terrain.report.gzipBytes,
    animatedPlacements: terrain.report.animatedCellsBakedAtFirstFrame,
  },
  animation: {
    sourceSequences: terrain.animationSequences.length,
    atlases: cooked.atlases.length,
    atlasBytes: cooked.atlases.reduce((sum, atlas) => sum + atlas.png.byteLength, 0),
  },
  animatedRepository: {
    entries: animatedSplit.entries.length,
    entryBytes: animatedSplit.entries.reduce((sum, entry) => sum + entry.bytes.byteLength, 0),
  },
  npcSrcRepository: {
    entries: npcSrcSplit.entries.length,
    entryBytes: npcSrcSplit.entries.reduce((sum, entry) => sum + entry.bytes.byteLength, 0),
  },
  characters: characters.report,
  battle: battle.report,
};
writeFileSync(join(ROOT, "data/g6-assets-report.json"), jsonBytes(assetReport));

console.log(
  `G6 assets: ${project.maps.length} maps, ${terrain.report.entries} TILESET entries, ` +
  `${characters.report.walkers} NPC walkers + player, ${cooked.atlases.length} animated atlases, ` +
  `${collisionBodies} removable collision bodies`,
);
console.log(
  `map repository: ${split.entries.length} entries, ${split.files[0]!.bytes.byteLength} shell bytes, ` +
  `${split.entries.reduce((sum, entry) => sum + entry.bytes.byteLength, 0)} map bytes`,
);
console.log(`terrain pak: ${terrain.report.pakBytes} bytes (${terrain.report.gzipBytes} gzip)`);
console.log(
  `battle ${battle.report.scope}: ${battle.report.counts.monsters} monsters, ` +
  `${battle.report.counts.techniques} techniques, ${battle.report.art.files} textures, ` +
  `${battle.report.art.pakBytes} battle-only pak bytes`,
);
console.log(
  `battle repository: ${battle.report.battleRepository.entries} entries, ` +
  `${battle.report.battleRepository.shellBytes} shell bytes, ` +
  `${battle.report.battleRepository.entryBytes} shard bytes`,
);
console.log(
  `animated repository: ${animatedSplit.entries.length} entries, ` +
  `${animatedSplit.entries.reduce((sum, entry) => sum + entry.bytes.byteLength, 0)} shard bytes`,
);
console.log(
  `npc-src repository: ${npcSrcSplit.entries.length} entries, ` +
  `${npcSrcSplit.entries.reduce((sum, entry) => sum + entry.bytes.byteLength, 0)} shard bytes`,
);
