// One-command deterministic G6 cook: K1 events + streamed terrain + R2 art.
// Usage: TUXEMON_SRC=/path/to/Tuxemon bun gen-assets.ts

import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { cookAnimationAtlases, animatedManifestSource } from "./vendor/pocket-rpgkit/tools/lib/animated.ts";
import type { GameAssets } from "./vendor/pocket-rpgkit/src/ui/game-assets.ts";
import type { PlayerFrames } from "./vendor/pocket-rpgkit/src/ui/PlayerSprite.tsx";
import type { Project } from "./vendor/pocket-rpgkit/src/engine/types.ts";
import { cookCharacters } from "./importer/characters.ts";
import { coverageMarkdown, jsonBytes } from "./importer/index.ts";
import { availableMapIds, buildProject, G6_IMPORT_OPTIONS } from "./importer/project.ts";
import { applyTerrain, writeTerrain } from "./importer/terrain.ts";

const ROOT = import.meta.dir;
const DIST = join(ROOT, "dist");
mkdirSync(DIST, { recursive: true });

const terrain = writeTerrain({ outputRoot: ROOT });
const imported = buildProject(availableMapIds(), G6_IMPORT_OPTIONS);
let project = applyTerrain(imported.project, terrain.fragment);
// The G1 one-tile sheet is now unused: every ground id and passage mask is
// owned by the generated terrain sheet.
project = {
  ...project,
  sheets: project.sheets.filter((sheet) => sheet.id !== "tux"),
  maps: project.maps.map((map) => ({ ...map, sheets: map.sheets?.filter((sheet) => sheet !== "tux") })),
};

const characters = await cookCharacters(project, { outputRoot: ROOT });
project = characters.project;

// Animated tile atlases are globally shared by equal RGBA sequences.
const animDir = join(ROOT, "assets/anim");
rmSync(animDir, { recursive: true, force: true });
mkdirSync(animDir, { recursive: true });
const cooked = cookAnimationAtlases(terrain.animationSequences, {
  directory: "assets/anim",
  prefix: "terrain",
});
for (const atlas of cooked.atlases) {
  const path = join(ROOT, atlas.file);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, atlas.png);
}
const animatedMaps = Object.entries(terrain.animations).map(([id, cells]) => ({
  id,
  tiles: cells.map((cell) => {
    const sprite = cooked.atlasFor.get(cell.sequence);
    if (!sprite) throw new Error(`gen-assets: no atlas for ${cell.sequence}`);
    return { x: cell.x, y: cell.y, above: cell.above, sprite };
  }),
}));

writeFileSync(join(ROOT, "sprites.json"), jsonBytes(cooked.spritesJson));
writeFileSync(join(ROOT, "images.json"), jsonBytes(characters.imagesJson));
writeFileSync(join(DIST, "project.json"), jsonBytes(project));
writeFileSync(join(DIST, "variable-enums.json"), jsonBytes(imported.variables));
writeFileSync(join(DIST, "import-report.json"), jsonBytes(imported.report));
writeFileSync(join(ROOT, "findings/G1-coverage.md"), coverageMarkdown(imported.report));

function gameAssetsSource(
  npcSrc: GameAssets["npcSrc"],
  player: PlayerFrames,
): string {
  return (
    "// AUTO-GENERATED by gen-assets.ts — do not edit.\n" +
    'import type { GameAssets, NpcArt } from "../vendor/pocket-rpgkit/src/ui/game-assets.ts";\n' +
    'import type { PlayerFrames } from "../vendor/pocket-rpgkit/src/ui/PlayerSprite.tsx";\n' +
    'import { TERRAIN_ORDER, TERRAIN_STREAM, TERRAIN_WORLD } from "./terrain-assets.ts";\n\n' +
    `export const NPC_SRC: Readonly<Record<string, NpcArt>> = ${JSON.stringify(npcSrc, null, 2)};\n\n` +
    `export const PLAYER: PlayerFrames = ${JSON.stringify(player, null, 2)};\n\n` +
    `export const ANIMATED = ${animatedManifestSource(animatedMaps)} as const;\n\n` +
    "export const GAME_ASSETS: GameAssets = {\n" +
    "  ground: {},\n" +
    "  upper: {},\n" +
    "  chunkColumns: {},\n" +
    "  maxChunks: 1,\n" +
    "  world: TERRAIN_WORLD,\n" +
    "  order: TERRAIN_ORDER,\n" +
    "  npcSrc: NPC_SRC,\n" +
    "  player: PLAYER,\n" +
    "  playerHeight: 32,\n" +
    "  stream: TERRAIN_STREAM,\n" +
    "  animated: ANIMATED,\n" +
    "};\n"
  );
}

writeFileSync(join(ROOT, "ui/game-assets.ts"), gameAssetsSource(characters.npcSrc, characters.player));

const collisionBodies = project.maps.reduce(
  (sum, map) => sum + (map.events ?? []).filter((event) => event.name?.startsWith("collision:")).length,
  0,
);
const assetReport = {
  format: "pocket-tuxemon/g6-assets/v1",
  sourceRevision: terrain.report.sourceRevision,
  project: {
    maps: project.maps.length,
    collisionBodies,
    options: G6_IMPORT_OPTIONS,
  },
  terrain: {
    entries: terrain.report.entries,
    pakBytes: terrain.report.pakBytes,
    gzipBytes: terrain.report.gzipBytes,
    animatedPlacements: terrain.report.animatedCellsBakedAtFirstFrame,
  },
  animation: {
    sourceSequences: terrain.animationSequences.length,
    atlases: cooked.atlases.length,
    atlasBytes: cooked.atlases.reduce((sum, atlas) => sum + atlas.png.byteLength, 0),
  },
  characters: characters.report,
};
writeFileSync(join(ROOT, "data/g6-assets-report.json"), jsonBytes(assetReport));

console.log(
  `G6 assets: ${project.maps.length} maps, ${terrain.report.entries} TILESET entries, ` +
  `${characters.report.walkers} NPC walkers + player, ${cooked.atlases.length} animated atlases, ` +
  `${collisionBodies} removable collision bodies`,
);
console.log(`terrain pak: ${terrain.report.pakBytes} bytes (${terrain.report.gzipBytes} gzip)`);
