// Localized battle display names (monster species, techniques, items),
// keyed by slug. Both tables are generated by the importer
// (data/battle-names(.zh_CN).json) from the catalog: the English table
// carries the en_US names (e.g. av8r -> "AV8R", not "Av8r"), the zh_CN
// table the merged Chinese names. The PSP build swaps ui/zh-data.ts for an
// English-only stub, so the PSP bundle carries no zh_CN battle names.

import { zhData } from "../ui/zh-data.ts";
import enNamesJson from "../data/battle-names.json";
import { battleSceneLang } from "../ui/battle-scene-locale.ts";
import type { GameLang } from "./extension.ts";

export interface BattleNames {
  monsters: Record<string, string>;
  techniques: Record<string, string>;
  items: Record<string, string>;
}

const zhNames = zhData.names as unknown as BattleNames;
const enNames = enNamesJson as unknown as BattleNames;

const titleCase = (slug: string): string => slug
  .split("_")
  .map((part) => part ? part[0]!.toUpperCase() + part.slice(1) : part)
  .join(" ");

export type BattleNameKind = "monster" | "technique" | "item";

const TABLE_KEY: Record<BattleNameKind, keyof BattleNames> = {
  monster: "monsters",
  technique: "techniques",
  item: "items",
};

function tableFor(lang: GameLang, kind: BattleNameKind): Record<string, string> {
  return (lang === "zh_CN" ? zhNames : enNames)[TABLE_KEY[kind]];
}

/** Resolve a battle slug to its display name in the active language. */
export function battleDisplayName(kind: BattleNameKind, slug: string): string {
  return battleDisplayNameFor(battleSceneLang(), kind, slug);
}

/** Resolve a battle slug to its display name in an explicit language. The
 *  text-token resolver uses this instead of battleDisplayName() so a headless
 *  zh_CN session (which does not call setBattleSceneLang) still resolves
 *  monster names in Chinese. */
export function battleDisplayNameFor(lang: GameLang, kind: BattleNameKind, slug: string): string {
  const hit = tableFor(lang, kind)[slug];
  if (hit) return hit;
  return titleCase(slug);
}
