// Localized battle display names (monster species, techniques, items),
// keyed by slug. The zh_CN table is generated by the importer
// (data/battle-names.zh_CN.json) from the merged catalog; the English build
// keeps title-cased slugs, which already match the en_US names. The PSP
// build swaps ui/zh-data.ts for an English-only stub, so the PSP bundle
// carries no zh_CN battle names.

import { zhData } from "../ui/zh-data.ts";
import { battleSceneLang } from "../ui/battle-scene-locale.ts";

export interface BattleNames {
  monsters: Record<string, string>;
  techniques: Record<string, string>;
  items: Record<string, string>;
}

const zhNames = zhData.names as unknown as BattleNames;

const titleCase = (slug: string): string => slug
  .split("_")
  .map((part) => part ? part[0]!.toUpperCase() + part.slice(1) : part)
  .join(" ");

export type BattleNameKind = "monster" | "technique" | "item";

const TABLE_KEY: Record<BattleNameKind, keyof BattleNames> = {
  monster: "monsters",
  technique: "techniques",
  item: "items",
};

function table(kind: BattleNameKind): Record<string, string> {
  return zhNames[TABLE_KEY[kind]];
}

/** Resolve a battle slug to its display name in the active language. */
export function battleDisplayName(kind: BattleNameKind, slug: string): string {
  if (battleSceneLang() === "zh_CN") {
    const hit = table(kind)[slug];
    if (hit) return hit;
  }
  return titleCase(slug);
}
