import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  availableMapIds,
  buildProject,
  DEFAULT_MAPS,
  KIT_V2_IMPORT_OPTIONS,
  type ImportOptions,
  type ImportReport,
} from "./project.ts";

export interface ImportPaths {
  project: string;
  variables: string;
  report: string;
  coverage: string;
}

export function jsonBytes(value: unknown): string {
  return JSON.stringify(value, null, 1) + "\n";
}

export function coverageMarkdown(report: ImportReport): string {
  const { actions, conditions } = report.coverage;
  const actionGap = actions.summary.tier1.requiredUses - actions.summary.tier1.uses;
  const conditionGap = conditions.summary.tier1.requiredUses - conditions.summary.tier1.uses;
  const summary = (kind: string, value: typeof actions.summary) =>
    `| ${kind} | ${value.types} | ${value.uses} | ${value.native} | ${value.degraded} | ${value.placeholder} | ${value.dropped} | ${value.tier1.uses} / ${value.tier1.requiredUses} (${value.tier1.percent.toFixed(2)}% / ${value.tier1.requiredPercent.toFixed(1)}%) |`;
  const rows = (kind: string, values: typeof actions.rows) => values
    .map((row) =>
      `| ${kind} | \`${row.type}\` | ${row.native} | ${row.degraded} | ${row.placeholder} | ${row.dropped} | ${row.total} |`
    )
    .join("\n");
  const repairs = report.transferRepairs.length
    ? report.transferRepairs.map((repair) =>
      `- \`${repair.sourceMap}\` → \`${repair.targetMap}\`: requested (${repair.requested.x}, ${repair.requested.y}), clamped (${repair.clamped.x}, ${repair.clamped.y}), emitted (${repair.emitted.x}, ${repair.emitted.y})`
    ).join("\n")
    : "- None.";
  return `# G1 import coverage

Generated by \`bun run import\` from the pinned Tuxemon source. Counts use the
per-file source view: shared scenario YAML is counted once. Dispositions are
recorded inside the converter branch that handles each action/condition, using
the first deterministic (map-id sorted) materialization of a shared event.
When conversion discards a whole event, every source rule in it is Dropped.

## Summary

| Kind | Kinds | Uses | Native | Degraded | Placeholder | Dropped | S1 T1 baseline |
|---|---:|---:|---:|---:|---:|---:|---:|
${summary("Actions", actions.summary)}
${summary("Conditions", conditions.summary)}

The S1 acceptance baselines are 6,246 action uses (45.9%) and 4,591
condition uses (53.0%). Only T1 source types whose disposition is Native or
Degraded count toward them. This import records ${actions.summary.tier1.uses}
(${actions.summary.tier1.percent.toFixed(2)}%) and ${conditions.summary.tier1.uses}
(${conditions.summary.tier1.percent.toFixed(2)}%), respectively: ${actionGap}
action uses and ${conditionGap} condition uses below the S1 baselines. The old
type-table Native figure was 5,448 / 13,617 (40.0%); conversion-path accounting
supersedes it with ${actions.summary.native} / ${actions.summary.uses}
(${actions.summary.nativePercent.toFixed(1)}%). “Executable”
(native + degraded + deliberate P1 placeholder) is
${actions.summary.executablePercent.toFixed(1)}% for actions and
${conditions.summary.executablePercent.toFixed(1)}% for conditions.

Definitions:

- **Native**: represented by current RPG Kit v1 commands without a gameplay loss.
- **Degraded**: runs in v1 with a documented limitation or importer lowering.
- **Placeholder**: deliberate P1 behavior for battle/monster state.
- **Dropped**: no equivalent output, including rules inside an event that the
  converter proves cannot start or otherwise omits. Per-disposition reasons are
  retained in \`dist/import-report.json\`.

## Transfer repairs

The generated project has ${report.transferErrors.length} invalid transfers.
${report.transferRepairs.length} out-of-range coordinates in the upstream data
are clamped deterministically. If the clamped cell has no walkable exit, a
four-neighbour BFS with fixed tie-breaking selects the nearest walkable cell:

${repairs}

## Actions

| Kind | Source type | Native | Degraded | Placeholder | Dropped | Total |
|---|---|---:|---:|---:|---:|---:|
${rows("Action", actions.rows)}

## Conditions

Condition keys include the \`is\` / \`not\` operator, matching S1's 64-pair
census.

| Kind | Source type | Native | Degraded | Placeholder | Dropped | Total |
|---|---|---:|---:|---:|---:|---:|
${rows("Condition", conditions.rows)}
`;
}

export function writeImport(
  mapIds: readonly string[],
  outDir = resolve(import.meta.dir, "../dist"),
  options: Partial<ImportOptions> = {},
): ImportPaths {
  const result = buildProject(mapIds, options);
  if (result.report.schemaErrors.length) {
    const detail = result.report.schemaErrors
      .slice(0, 20)
      .map((error) => `${error.path}: ${error.msg}`)
      .join("\n");
    throw new Error(`${result.report.schemaErrors.length} schema error(s)\n${detail}`);
  }
  if (result.report.transferErrors.length) {
    const detail = result.report.transferErrors
      .slice(0, 20)
      .map((error) =>
        `${error.sourceMap}/${error.event}: ${error.targetMap}@${error.x},${error.y} (${error.reason})`
      )
      .join("\n");
    throw new Error(`${result.report.transferErrors.length} invalid transfer(s)\n${detail}`);
  }
  mkdirSync(outDir, { recursive: true });
  const paths: ImportPaths = {
    project: resolve(outDir, "project.json"),
    variables: resolve(outDir, "variable-enums.json"),
    report: resolve(outDir, "import-report.json"),
    coverage: resolve(import.meta.dir, "../findings/G1-coverage.md"),
  };
  writeFileSync(paths.project, jsonBytes(result.project));
  writeFileSync(paths.variables, jsonBytes(result.variables));
  writeFileSync(paths.report, jsonBytes(result.report));
  writeFileSync(paths.coverage, coverageMarkdown(result.report));
  return paths;
}

function main(): void {
  const args = process.argv.slice(2);
  const named = args.filter((arg) => !arg.startsWith("--"));
  const selected = args.includes("--sample")
    ? DEFAULT_MAPS
    : named.length ? named : availableMapIds();
  const paths = writeImport(
    selected,
    resolve(import.meta.dir, "../dist"),
    args.includes("--kit=v2") ? KIT_V2_IMPORT_OPTIONS : {},
  );
  console.log(`Imported ${selected.length} map(s); schema errors: 0`);
  console.log(`Project: ${paths.project}`);
  console.log(`Variables: ${paths.variables}`);
  console.log(`Report: ${paths.report}`);
  console.log(`Coverage: ${paths.coverage}`);
}

if (import.meta.main) main();
