// Run the complete G6 cook twice and prove that every generated byte is
// stable. This covers K1 project JSON, streamed terrain, R2 characters,
// animated atlases, manifests, and coverage/report outputs.

import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const GENERATED = [
  "assets/anim",
  "assets/characters",
  "assets/stream",
  "data/terrain.json",
  "data/terrain-animations.json",
  "data/terrain-report.json",
  "data/g6-assets-report.json",
  "dist/project.json",
  "dist/import-report.json",
  "dist/variable-enums.json",
  "findings/G1-coverage.md",
  "images.json",
  "pak.json",
  "sprites.json",
  "ui/game-assets.ts",
  "ui/terrain-assets.ts",
] as const;

interface Snapshot {
  sha256: string;
  files: number;
  bytes: number;
  entries: Map<string, string>;
}

function filesAt(path: string): string[] {
  if (!statSync(path).isDirectory()) return [path];
  const out: string[] = [];
  for (const entry of readdirSync(path, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const child = join(path, entry.name);
    if (entry.isDirectory()) out.push(...filesAt(child));
    else if (entry.isFile()) out.push(child);
  }
  return out;
}

function snapshot(): Snapshot {
  const tree = createHash("sha256");
  const entries = new Map<string, string>();
  let bytes = 0;
  for (const source of GENERATED) {
    for (const path of filesAt(join(ROOT, source))) {
      const name = relative(ROOT, path).replaceAll("\\", "/");
      const data = readFileSync(path);
      const digest = createHash("sha256").update(data).digest("hex");
      entries.set(name, digest);
      tree.update(name).update("\0").update(data).update("\0");
      bytes += data.byteLength;
    }
  }
  return { sha256: tree.digest("hex"), files: entries.size, bytes, entries };
}

function generate(): void {
  const proc = Bun.spawnSync({
    cmd: [process.execPath, join(ROOT, "gen-assets.ts")],
    cwd: ROOT,
    stdout: "inherit",
    stderr: "inherit",
  });
  if (proc.exitCode !== 0) throw new Error(`G6 determinism: generator exited ${proc.exitCode}`);
}

generate();
const first = snapshot();
generate();
const second = snapshot();
const names = new Set([...first.entries.keys(), ...second.entries.keys()]);
const changed = [...names].filter((name) => first.entries.get(name) !== second.entries.get(name));
if (changed.length) throw new Error(`G6 determinism: changed files:\n${changed.join("\n")}`);
if (first.sha256 !== second.sha256) throw new Error("G6 determinism: aggregate digest changed");
console.log(
  `G6 determinism: PASS files=${second.files} bytes=${second.bytes} sha256=${second.sha256}`,
);
