// Neighbour character preview coverage at every mainline chapter.
//
// The import report gives the sandbox verdict at the new-game state. This
// verifier restores each chapter snapshot of data/chapters.json and runs the
// same verdict for every map (the renderer's: the game's preview hooks, the
// static preview as fallback), then checks:
//   - the new-game result equals the one in dist/import-report.json;
//   - no mainline (spyder_*) event is rejected at any chapter;
//   - the sandbox never writes the live state (canonical hash unchanged).
// Writes reports/preview-coverage.md and reports/preview-coverage.zh_CN.md.
//
// Usage: bun tools/verify-preview-coverage.ts

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, resolve } from "node:path";

import { createTuxemonSessionOptions } from "../battle/game.ts";
import { canonicalJson } from "../vendor/pocket-rpgkit/src/engine/save.ts";
import { restoreSessionEnvelope } from "../vendor/pocket-rpgkit/src/engine/save-restore.ts";
import { createSession, startSession, type SessionState } from "../vendor/pocket-rpgkit/src/engine/session.ts";
import { SANDBOX_PREVIEW_REJECT_REASONS } from "../vendor/pocket-rpgkit/src/engine/world-preview-sandbox.ts";
import type { MapDef } from "../vendor/pocket-rpgkit/src/engine/types.ts";
import {
  previewCoverageOf,
  sandboxPreviews,
  type PreviewCoverageReport,
  type PreviewCoverageTotals,
} from "../importer/preview-coverage.ts";
import { readInlineProject } from "./generated-project.ts";

const ROOT = resolve(import.meta.dir, "..");
const project = readInlineProject(ROOT);
const session = createSession(project, 60, createTuxemonSessionOptions(project, "seamless-v1", { immutableState: true }));
const mapIds = project.maps.map((map: MapDef) => map.id);
const chapters = JSON.parse(readFileSync(join(ROOT, "data/chapters.json"), "utf8")) as {
  chapters: { id: string; title: string; map: string; snapshot: string }[];
};
const imported = JSON.parse(readFileSync(join(ROOT, "dist/import-report.json"), "utf8")) as {
  preview?: PreviewCoverageReport;
};

const digest = (value: unknown): string => createHash("sha256").update(canonicalJson(value)).digest("hex");

interface Row {
  id: string;
  title: string;
  map: string;
  all: PreviewCoverageTotals;
  mainline: PreviewCoverageTotals;
  rejectedMaps: string[];
  ms: number;
}

const failures: string[] = [];

function evaluate(id: string, title: string, live: SessionState): { row: Row; coverage: ReturnType<typeof previewCoverageOf> } {
  const before = digest(live);
  const started = performance.now();
  const previews = sandboxPreviews(session, live, mapIds);
  const ms = performance.now() - started;
  if (digest(live) !== before) failures.push(`${id}: the sandbox changed the live state`);
  const coverage = previewCoverageOf(previews);
  const rejectedMaps = coverage.perMap.filter((row) => row.rejected > 0).map((row) => row.mapId);
  if (coverage.mainline.rejected !== 0) {
    failures.push(`${id}: ${coverage.mainline.rejected} mainline events rejected (${rejectedMaps.filter((m) => m.startsWith("spyder_")).join(", ")})`);
  }
  return { row: { id, title, map: live.mapId, all: coverage.all, mainline: coverage.mainline, rejectedMaps, ms }, coverage };
}

const rows: Row[] = [];
const fresh = evaluate("new-game", "New game", startSession(project, session));
rows.push(fresh.row);
if (!imported.preview) {
  failures.push("dist/import-report.json has no preview coverage (rerun bun run import)");
} else if (canonicalJson(fresh.coverage) !== canonicalJson({
  all: imported.preview.all,
  mainline: imported.preview.mainline,
  perMap: imported.preview.perMap,
})) {
  failures.push("new-game coverage differs from dist/import-report.json (rerun bun run import)");
}
for (const chapter of chapters.chapters) {
  rows.push(evaluate(chapter.id, chapter.title, restoreSessionEnvelope(session, chapter.snapshot)).row);
}

function reasons(totals: PreviewCoverageTotals): string {
  const used = SANDBOX_PREVIEW_REJECT_REASONS.filter((reason) => totals.reasons[reason] > 0);
  return used.length ? used.map((reason) => `${reason}:${totals.reasons[reason]}`).join(", ") : "—";
}

function markdown(zh: boolean): string {
  const head = zh
    ? `# 邻图 NPC 预览覆盖率（沙盒口径，各主线章节）

由 \`bun run verify:preview:coverage\` 生成。每个章节存档恢复后，对全部 ${mapIds.length} 张图跑一遍渲染器同款的沙盒判定
（游戏钩子 + 静态规则后备）。「可预览率」= 可预览 / (可预览 + 拒绝)；隐藏 = 进图后不画任何东西的事件。
主线 = \`spyder_*\` 地图。

| 章节 | 所在地图 | 全部：可预览 / 隐藏 / 拒绝 | 可预览率 | 有人的图 | 主线：可预览 / 隐藏 / 拒绝 | 拒绝原因 | 耗时 (Bun) |
|---|---|---:|---:|---:|---:|---|---:|
`
    : `# Neighbour character preview coverage (sandboxed entry, every mainline chapter)

Generated by \`bun run verify:preview:coverage\`. Each chapter snapshot is
restored and the renderer's sandbox verdict (game hooks, static fallback) runs
for all ${mapIds.length} maps. "Previewable share" = previewable / (previewable +
rejected); hidden events paint nothing on entry. Mainline = \`spyder_*\` maps.

| Chapter | Map | All: previewable / hidden / rejected | Previewable share | Maps with characters | Mainline: previewable / hidden / rejected | Reject reasons | Time (Bun) |
|---|---|---:|---:|---:|---:|---|---:|
`;
  const body = rows.map((row) =>
    `| ${row.id} | \`${row.map}\` | ${row.all.previewed} / ${row.all.hidden} / ${row.all.rejected} | ${row.all.previewablePercent}% | ${row.all.mapsWithPreview} | ${row.mainline.previewed} / ${row.mainline.hidden} / ${row.mainline.rejected} | ${reasons(row.all)} | ${row.ms.toFixed(0)} ms |`
  ).join("\n");
  const maps = [...new Set(rows.flatMap((row) => row.rejectedMaps))].sort();
  const tail = zh
    ? `\n\n有拒绝事件的地图（任一章节）：${maps.length ? maps.map((m) => `\`${m}\``).join("、") : "无"}。\n`
    : `\n\nMaps with a rejected event (any chapter): ${maps.length ? maps.map((m) => `\`${m}\``).join(", ") : "none"}.\n`;
  return head + body + tail;
}

mkdirSync(join(ROOT, "reports"), { recursive: true });
writeFileSync(join(ROOT, "reports/preview-coverage.md"), markdown(false));
writeFileSync(join(ROOT, "reports/preview-coverage.zh_CN.md"), markdown(true));
for (const row of rows) {
  console.log(
    `PREVIEW ${row.id.padEnd(18)} map=${row.map} all=${row.all.previewed}/${row.all.hidden}/${row.all.rejected}`
    + ` share=${row.all.previewablePercent}% mainline=${row.mainline.previewed}/${row.mainline.hidden}/${row.mainline.rejected}`
    + ` reasons=${reasons(row.all)} ms=${row.ms.toFixed(0)}`,
  );
}
if (failures.length) {
  for (const failure of failures) console.error(`PREVIEW FAIL ${failure}`);
  process.exit(1);
}
console.log(`PREVIEW PASS ${rows.length} states, mainline 0 rejected; reports/preview-coverage.md`);
