// Run the complete G6 cook twice and prove that every generated byte is
// stable. This covers K1 project JSON, streamed terrain, R2 characters,
// animated atlases, manifests, and coverage/report outputs.

import { createHash } from "node:crypto";
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const GENERATED = [
  "assets/anim",
  "assets/battle",
  "assets/characters",
  "assets/stream",
  "data/terrain.json",
  "data/terrain-animations.json",
  "data/terrain-report.json",
  "data/g6-assets-report.json",
  "data/battle-db.json",
  "data/battle-runtime-db.json",
  "data/battle-assets-report.json",
  "dist/maps",
  "dist/battle",
  "dist/battle-runtime-shell.json",
  "dist/animated",
  "dist/npc-src",
  "dist/terrain-stream",
  "dist/project.json",
  "dist/project-shell.json",
  "dist/import-report.json",
  "dist/variable-enums.json",
  "dist/world-index.json",
  "reports/G1-coverage.md",
  "images.json",
  "pak.json",
  "sprites.json",
  "ui/game-assets.ts",
  "ui/battle-assets.ts",
  "ui/terrain-assets.ts",
  "ui/npc-src-assets.ts",
  "ui/animated-assets.ts",
] as const;

interface Snapshot {
  sha256: string;
  files: number;
  bytes: number;
  entries: Map<string, string>;
}

function filesAt(path: string): string[] {
  if (!statSync(path).isDirectory()) return [path];
  const out: string[] = [];
  for (const entry of readdirSync(path, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const child = join(path, entry.name);
    if (entry.isDirectory()) out.push(...filesAt(child));
    else if (entry.isFile()) out.push(child);
  }
  return out;
}

function snapshot(root: string): Snapshot {
  const tree = createHash("sha256");
  const entries = new Map<string, string>();
  let bytes = 0;
  for (const source of GENERATED) {
    for (const path of filesAt(join(root, source))) {
      const name = relative(root, path).replaceAll("\\", "/");
      const data = readFileSync(path);
      const digest = createHash("sha256").update(data).digest("hex");
      entries.set(name, digest);
      tree.update(name).update("\0").update(data).update("\0");
      bytes += data.byteLength;
    }
  }
  return { sha256: tree.digest("hex"), files: entries.size, bytes, entries };
}

function generate(outputRoot: string): void {
  const proc = Bun.spawnSync({
    cmd: [process.execPath, join(ROOT, "gen-assets.ts")],
    cwd: ROOT,
    env: { ...process.env, G6_OUTPUT_ROOT: outputRoot },
    stdout: "inherit",
    stderr: "inherit",
  });
  if (proc.exitCode !== 0) throw new Error(`G6 determinism: generator exited ${proc.exitCode}`);
}

const scratchParent = resolve(process.env.G6_SCRATCH_ROOT ?? join(tmpdir(), "pocket-tuxemon"));
mkdirSync(scratchParent, { recursive: true });
const firstRoot = mkdtempSync(join(scratchParent, "g6-determinism-a-"));
const secondRoot = mkdtempSync(join(scratchParent, "g6-determinism-b-"));
try {
  generate(firstRoot);
  const first = snapshot(firstRoot);
  generate(secondRoot);
  const second = snapshot(secondRoot);
  const names = new Set([...first.entries.keys(), ...second.entries.keys()]);
  const changed = [...names].filter((name) => first.entries.get(name) !== second.entries.get(name));
  if (changed.length) throw new Error(`G6 determinism: changed files:\n${changed.join("\n")}`);
  if (first.sha256 !== second.sha256) throw new Error("G6 determinism: aggregate digest changed");
  console.log(
    `G6 determinism: PASS isolatedRoots=2 files=${second.files} bytes=${second.bytes} sha256=${second.sha256}`,
  );
} finally {
  rmSync(firstRoot, { recursive: true, force: true });
  rmSync(secondRoot, { recursive: true, force: true });
}
