// AUTO-GENERATED by gen-assets.ts — do not edit.
// Lazy choice_monster row icons: sprite -> on-demand IMG entry. The texture
// is uploaded only when a choice menu first resolves the sprite.
export const CHOICE_ICON_TEXTURES: Readonly<Record<string, { entry: string }>> = {
  "tux_monster_menu_budaye": {
    "entry": "choice-icons/tux_monster_menu_budaye.img"
  },
  "tux_monster_menu_dollfin": {
    "entry": "choice-icons/tux_monster_menu_dollfin.img"
  },
  "tux_monster_menu_fruitera": {
    "entry": "choice-icons/tux_monster_menu_fruitera.img"
  },
  "tux_monster_menu_grintot": {
    "entry": "choice-icons/tux_monster_menu_grintot.img"
  },
  "tux_monster_menu_hydrone": {
    "entry": "choice-icons/tux_monster_menu_hydrone.img"
  },
  "tux_monster_menu_ignibus": {
    "entry": "choice-icons/tux_monster_menu_ignibus.img"
  },
  "tux_monster_menu_memnomnom": {
    "entry": "choice-icons/tux_monster_menu_memnomnom.img"
  },
  "tux_monster_menu_rockitten": {
    "entry": "choice-icons/tux_monster_menu_rockitten.img"
  }
};
