// AUTO-GENERATED by gen-assets.ts — do not edit.
// The chapter snapshots and the mainline tape live in the pak (entries
// below) and are read on demand when a chapter is first selected.
export const DEMO_TAPE_ENTRY = "demo/tape.bin";
export const DEMO_SNAPSHOTS_ENTRY = "demo/chapters.json";

export const DEMO_CHAPTER_INDEX = [
  {
    "id": "bedroom",
    "title": "Bedroom (new game)",
    "worldTraversal": "seamless-v1",
    "frame": 0,
    "suffixFrames": 198568,
    "timelineFrame": 0
  },
  {
    "id": "paper-town",
    "title": "Paper Town",
    "worldTraversal": "seamless-v1",
    "frame": 1399,
    "suffixFrames": 197169,
    "timelineFrame": 1399
  },
  {
    "id": "before-billie",
    "title": "Before the first Billie battle",
    "worldTraversal": "seamless-v1",
    "frame": 1924,
    "suffixFrames": 196644,
    "timelineFrame": 1924
  },
  {
    "id": "starter",
    "title": "Starter chosen",
    "worldTraversal": "seamless-v1",
    "frame": 3692,
    "suffixFrames": 194876,
    "timelineFrame": 3692
  },
  {
    "id": "route-1",
    "title": "Route 1",
    "worldTraversal": "seamless-v1",
    "frame": 3982,
    "suffixFrames": 194586,
    "timelineFrame": 3982
  },
  {
    "id": "cotton-town",
    "title": "Cotton Town",
    "worldTraversal": "seamless-v1",
    "frame": 5384,
    "suffixFrames": 193184,
    "timelineFrame": 5384
  },
  {
    "id": "city-park",
    "title": "City Park",
    "worldTraversal": "seamless-v1",
    "frame": 44953,
    "suffixFrames": 153615,
    "timelineFrame": 44953
  },
  {
    "id": "route-3-north",
    "title": "Route 3 north end",
    "worldTraversal": "seamless-v1",
    "frame": 110244,
    "suffixFrames": 88324,
    "timelineFrame": 110244
  },
  {
    "id": "flower-city",
    "title": "Flower City",
    "worldTraversal": "seamless-v1",
    "frame": 115002,
    "suffixFrames": 83566,
    "timelineFrame": 115002
  },
  {
    "id": "captain-returns",
    "title": "Captain's return",
    "worldTraversal": "seamless-v1",
    "frame": 121764,
    "suffixFrames": 76804,
    "timelineFrame": 121764
  },
  {
    "id": "candy-town",
    "title": "Candy Town",
    "worldTraversal": "seamless-v1",
    "frame": 164415,
    "suffixFrames": 34153,
    "timelineFrame": 164415
  },
  {
    "id": "greenwash-aardant",
    "title": "Greenwash (Aardant acquired)",
    "worldTraversal": "seamless-v1",
    "frame": 170801,
    "suffixFrames": 27767,
    "timelineFrame": 170801
  },
  {
    "id": "hospital-cure",
    "title": "Hospital cure",
    "worldTraversal": "seamless-v1",
    "frame": 172240,
    "suffixFrames": 26328,
    "timelineFrame": 172240
  },
  {
    "id": "omnichannel-open",
    "title": "Omnichannel passage opened",
    "worldTraversal": "seamless-v1",
    "frame": 179998,
    "suffixFrames": 18570,
    "timelineFrame": 179998
  },
  {
    "id": "radio-broadcast",
    "title": "Radio Tower broadcast",
    "worldTraversal": "seamless-v1",
    "frame": 185158,
    "suffixFrames": 13410,
    "timelineFrame": 185158
  },
  {
    "id": "kernel-briefing",
    "title": "Kernel quest briefing",
    "worldTraversal": "seamless-v1",
    "frame": 187029,
    "suffixFrames": 11539,
    "timelineFrame": 187029
  },
  {
    "id": "surfboard",
    "title": "Surfboard acquired",
    "worldTraversal": "seamless-v1",
    "frame": 188410,
    "suffixFrames": 10158,
    "timelineFrame": 188410
  },
  {
    "id": "route-b",
    "title": "Route B",
    "worldTraversal": "seamless-v1",
    "frame": 190589,
    "suffixFrames": 7979,
    "timelineFrame": 190589
  },
  {
    "id": "data-center",
    "title": "Data Center",
    "worldTraversal": "seamless-v1",
    "frame": 194101,
    "suffixFrames": 4467,
    "timelineFrame": 194101
  },
  {
    "id": "kernel-defeated",
    "title": "Kernel quest complete",
    "worldTraversal": "seamless-v1",
    "frame": 198557,
    "suffixFrames": 11,
    "timelineFrame": 198557
  }
] as const;

export const DEMO_WARP_SPAWNS = [
  {
    "id": "37707_tower",
    "x": 12,
    "y": 21
  },
  {
    "id": "37707_town",
    "x": 24,
    "y": 6
  },
  {
    "id": "37707_town_missing",
    "x": 24,
    "y": 6
  },
  {
    "id": "azure_town",
    "x": 41,
    "y": 23
  },
  {
    "id": "azure_town_hall",
    "x": 20,
    "y": 18
  },
  {
    "id": "bedroom_test",
    "x": 8,
    "y": 2
  },
  {
    "id": "buddha_mountain",
    "x": 3,
    "y": 89
  },
  {
    "id": "candy_town",
    "x": 7,
    "y": 38
  },
  {
    "id": "city1_mart_junkyard",
    "x": 11,
    "y": 4
  },
  {
    "id": "citypark",
    "x": 36,
    "y": 4
  },
  {
    "id": "citypark_house1",
    "x": 6,
    "y": 6
  },
  {
    "id": "classic_aerolume_city",
    "x": 1,
    "y": 17
  },
  {
    "id": "classic_gym_astra",
    "x": 10,
    "y": 18
  },
  {
    "id": "classic_gym_bravion",
    "x": 10,
    "y": 18
  },
  {
    "id": "classic_gym_ferrum",
    "x": 2,
    "y": 0
  },
  {
    "id": "classic_gym_granite",
    "x": 10,
    "y": 18
  },
  {
    "id": "classic_gym_marin",
    "x": 10,
    "y": 18
  },
  {
    "id": "classic_gym_mila",
    "x": 10,
    "y": 18
  },
  {
    "id": "classic_gym_orion",
    "x": 2,
    "y": 0
  },
  {
    "id": "classic_gym_pyra",
    "x": 10,
    "y": 18
  },
  {
    "id": "classic_gym_shade",
    "x": 2,
    "y": 0
  },
  {
    "id": "classic_gym_sylva",
    "x": 2,
    "y": 0
  },
  {
    "id": "classic_gym_voltessa",
    "x": 10,
    "y": 18
  },
  {
    "id": "classic_gym_vyre",
    "x": 2,
    "y": 0
  },
  {
    "id": "classic_gym_zephra",
    "x": 2,
    "y": 0
  },
  {
    "id": "classic_hearthrock_city",
    "x": 23,
    "y": 14
  },
  {
    "id": "classic_route_1",
    "x": 33,
    "y": 18
  },
  {
    "id": "classic_route_2",
    "x": 1,
    "y": 3
  },
  {
    "id": "classic_route_3",
    "x": 20,
    "y": 19
  },
  {
    "id": "classic_route_5",
    "x": 38,
    "y": 17
  },
  {
    "id": "classic_route_6",
    "x": 1,
    "y": 2
  },
  {
    "id": "classic_route_7",
    "x": 36,
    "y": 1
  },
  {
    "id": "classic_route_8",
    "x": 1,
    "y": 16
  },
  {
    "id": "classic_steamshore_city",
    "x": 31,
    "y": 5
  },
  {
    "id": "classic_stormpeak_city",
    "x": 35,
    "y": 4
  },
  {
    "id": "classic_thornwood_city",
    "x": 1,
    "y": 17
  },
  {
    "id": "classic_umbrastar_city",
    "x": 1,
    "y": 17
  },
  {
    "id": "classic_valorhold_city",
    "x": 27,
    "y": 13
  },
  {
    "id": "cotton_cafe",
    "x": 1,
    "y": 10
  },
  {
    "id": "cotton_cafe_basement",
    "x": 1,
    "y": 10
  },
  {
    "id": "cotton_cathedral",
    "x": 6,
    "y": 9
  },
  {
    "id": "cotton_daycare",
    "x": 2,
    "y": 7
  },
  {
    "id": "cotton_misa_house",
    "x": 4,
    "y": 2
  },
  {
    "id": "cotton_misa_house_upstairs",
    "x": 8,
    "y": 2
  },
  {
    "id": "cotton_scoop",
    "x": 5,
    "y": 9
  },
  {
    "id": "cotton_town",
    "x": 10,
    "y": 17
  },
  {
    "id": "cotton_underground",
    "x": 10,
    "y": 16
  },
  {
    "id": "dojo1",
    "x": 11,
    "y": 5
  },
  {
    "id": "dojo2",
    "x": 10,
    "y": 9
  },
  {
    "id": "dojo3",
    "x": 10,
    "y": 9
  },
  {
    "id": "downstairs_test",
    "x": 0,
    "y": 2
  },
  {
    "id": "dragonscave",
    "x": 12,
    "y": 38
  },
  {
    "id": "dryadsgrove",
    "x": 1,
    "y": 7
  },
  {
    "id": "eclipse_crystal_bank1",
    "x": 1,
    "y": 10
  },
  {
    "id": "eclipse_crystal_bank2",
    "x": 2,
    "y": 15
  },
  {
    "id": "eclipse_crystal_bank3",
    "x": 2,
    "y": 12
  },
  {
    "id": "eclipse_crystal_center",
    "x": 6,
    "y": 7
  },
  {
    "id": "eclipse_crystal_town",
    "x": 6,
    "y": 8
  },
  {
    "id": "eclipse_crystal_town_cafe",
    "x": 8,
    "y": 10
  },
  {
    "id": "eclipse_crystal_town_house",
    "x": 4,
    "y": 6
  },
  {
    "id": "eclipse_lion_mountain_high",
    "x": 39,
    "y": 13
  },
  {
    "id": "eclipse_lion_mountain_low",
    "x": 0,
    "y": 9
  },
  {
    "id": "eclipse_lion_mountain_middle",
    "x": 2,
    "y": 1
  },
  {
    "id": "eclipse_obsidian_center",
    "x": 6,
    "y": 9
  },
  {
    "id": "eclipse_obsidian_town",
    "x": 16,
    "y": 9
  },
  {
    "id": "eclipse_obsidian_town_house",
    "x": 4,
    "y": 6
  },
  {
    "id": "eclipse_park",
    "x": 38,
    "y": 13
  },
  {
    "id": "eclipse_park_cabin",
    "x": 6,
    "y": 4
  },
  {
    "id": "eclipse_park_cave",
    "x": 32,
    "y": 11
  },
  {
    "id": "eclipse_park_entrance",
    "x": 4,
    "y": 3
  },
  {
    "id": "eclipse_park_south",
    "x": 6,
    "y": 35
  },
  {
    "id": "eclipse_route7",
    "x": 35,
    "y": 1
  },
  {
    "id": "eclipse_routef",
    "x": 24,
    "y": 0
  },
  {
    "id": "eclipse_routeg",
    "x": 24,
    "y": 38
  },
  {
    "id": "eclipse_routeh",
    "x": 23,
    "y": 39
  },
  {
    "id": "eclipse_routei",
    "x": 26,
    "y": 10
  },
  {
    "id": "flower_city",
    "x": 3,
    "y": 18
  },
  {
    "id": "gadget_store1",
    "x": 0,
    "y": 3
  },
  {
    "id": "gaming_hall",
    "x": 1,
    "y": 0
  },
  {
    "id": "healing_center",
    "x": 6,
    "y": 9
  },
  {
    "id": "leather_scoop",
    "x": 5,
    "y": 9
  },
  {
    "id": "leather_shaft1",
    "x": 12,
    "y": 13
  },
  {
    "id": "leather_shaft2",
    "x": 4,
    "y": 8
  },
  {
    "id": "leather_town",
    "x": 24,
    "y": 10
  },
  {
    "id": "manhattan_beach",
    "x": 27,
    "y": 38
  },
  {
    "id": "mansion",
    "x": 2,
    "y": 15
  },
  {
    "id": "mansion_basement",
    "x": 7,
    "y": 20
  },
  {
    "id": "mansion_top",
    "x": 1,
    "y": 16
  },
  {
    "id": "maple_bedroom",
    "x": 8,
    "y": 2
  },
  {
    "id": "maple_house",
    "x": 11,
    "y": 2
  },
  {
    "id": "omnichannel0",
    "x": 1,
    "y": 5
  },
  {
    "id": "omnichannel1",
    "x": 1,
    "y": 3
  },
  {
    "id": "omnichannel2",
    "x": 1,
    "y": 12
  },
  {
    "id": "omnichannel3",
    "x": 1,
    "y": 12
  },
  {
    "id": "omnichannel4",
    "x": 1,
    "y": 12
  },
  {
    "id": "player_house_bedroom",
    "x": 1,
    "y": 3
  },
  {
    "id": "player_house_downstairs",
    "x": 1,
    "y": 2
  },
  {
    "id": "professor_lab",
    "x": 6,
    "y": 16
  },
  {
    "id": "route1",
    "x": 18,
    "y": 6
  },
  {
    "id": "route1_sanglorian",
    "x": 10,
    "y": 1
  },
  {
    "id": "route2",
    "x": 11,
    "y": 1
  },
  {
    "id": "route3",
    "x": 30,
    "y": 39
  },
  {
    "id": "route4",
    "x": 18,
    "y": 3
  },
  {
    "id": "route5",
    "x": 1,
    "y": 15
  },
  {
    "id": "route6",
    "x": 7,
    "y": 1
  },
  {
    "id": "routea",
    "x": 6,
    "y": 13
  },
  {
    "id": "routec",
    "x": 38,
    "y": 5
  },
  {
    "id": "rubberduck_cave_01",
    "x": 49,
    "y": 14
  },
  {
    "id": "rubberduck_city_01",
    "x": 12,
    "y": 12
  },
  {
    "id": "rubberduck_route_01",
    "x": 37,
    "y": 10
  },
  {
    "id": "russell_practice_1",
    "x": 1,
    "y": 0
  },
  {
    "id": "scoop1",
    "x": 19,
    "y": 3
  },
  {
    "id": "scoop2",
    "x": 7,
    "y": 4
  },
  {
    "id": "scoop3",
    "x": 5,
    "y": 3
  },
  {
    "id": "scoop4",
    "x": 9,
    "y": 20
  },
  {
    "id": "sphalian_center",
    "x": 6,
    "y": 9
  },
  {
    "id": "sphalian_town",
    "x": 21,
    "y": 14
  },
  {
    "id": "sphalian_town_house",
    "x": 5,
    "y": 6
  },
  {
    "id": "spyder_bedroom",
    "x": 8,
    "y": 2
  },
  {
    "id": "spyder_brideswood",
    "x": 1,
    "y": 27
  },
  {
    "id": "spyder_candy_cafe",
    "x": 4,
    "y": 7
  },
  {
    "id": "spyder_candy_center",
    "x": 14,
    "y": 5
  },
  {
    "id": "spyder_candy_hospital1",
    "x": 7,
    "y": 15
  },
  {
    "id": "spyder_candy_hospital2",
    "x": 11,
    "y": 15
  },
  {
    "id": "spyder_candy_hospital3",
    "x": 5,
    "y": 18
  },
  {
    "id": "spyder_candy_house1",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_candy_house2",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_candy_house3",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_candy_inn1",
    "x": 3,
    "y": 2
  },
  {
    "id": "spyder_candy_inn2",
    "x": 5,
    "y": 2
  },
  {
    "id": "spyder_candy_port",
    "x": 22,
    "y": 5
  },
  {
    "id": "spyder_candy_scoop",
    "x": 5,
    "y": 9
  },
  {
    "id": "spyder_candy_town",
    "x": 4,
    "y": 19
  },
  {
    "id": "spyder_citypark_house1",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_cotton_artshop",
    "x": 2,
    "y": 8
  },
  {
    "id": "spyder_cotton_cafe",
    "x": 8,
    "y": 10
  },
  {
    "id": "spyder_cotton_house1",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_cotton_house2",
    "x": 5,
    "y": 2
  },
  {
    "id": "spyder_cotton_scoop",
    "x": 5,
    "y": 9
  },
  {
    "id": "spyder_cotton_town",
    "x": 16,
    "y": 17
  },
  {
    "id": "spyder_cotton_tunnel",
    "x": 35,
    "y": 3
  },
  {
    "id": "spyder_datacenter",
    "x": 2,
    "y": 18
  },
  {
    "id": "spyder_diamond_hill",
    "x": 18,
    "y": 51
  },
  {
    "id": "spyder_dojo1",
    "x": 11,
    "y": 5
  },
  {
    "id": "spyder_dojo2",
    "x": 10,
    "y": 8
  },
  {
    "id": "spyder_dojo3",
    "x": 10,
    "y": 8
  },
  {
    "id": "spyder_dojo4",
    "x": 10,
    "y": 8
  },
  {
    "id": "spyder_downstairs",
    "x": 0,
    "y": 2
  },
  {
    "id": "spyder_flower_center",
    "x": 6,
    "y": 9
  },
  {
    "id": "spyder_flower_city",
    "x": 17,
    "y": 30
  },
  {
    "id": "spyder_flower_house1",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_flower_house2",
    "x": 2,
    "y": 7
  },
  {
    "id": "spyder_flower_petshop",
    "x": 1,
    "y": 6
  },
  {
    "id": "spyder_flower_scoop",
    "x": 5,
    "y": 9
  },
  {
    "id": "spyder_greenwash",
    "x": 14,
    "y": 19
  },
  {
    "id": "spyder_greenwash_greenhouse",
    "x": 1,
    "y": 7
  },
  {
    "id": "spyder_greenwash_level2",
    "x": 1,
    "y": 4
  },
  {
    "id": "spyder_greenwash_level3",
    "x": 13,
    "y": 2
  },
  {
    "id": "spyder_healing_center",
    "x": 6,
    "y": 9
  },
  {
    "id": "spyder_leather_center",
    "x": 6,
    "y": 9
  },
  {
    "id": "spyder_leather_gym",
    "x": 1,
    "y": 9
  },
  {
    "id": "spyder_leather_house1",
    "x": 4,
    "y": 6
  },
  {
    "id": "spyder_leather_house2",
    "x": 2,
    "y": 6
  },
  {
    "id": "spyder_leather_museum",
    "x": 0,
    "y": 10
  },
  {
    "id": "spyder_leather_scoop",
    "x": 5,
    "y": 9
  },
  {
    "id": "spyder_leather_shaft1",
    "x": 12,
    "y": 13
  },
  {
    "id": "spyder_leather_shaft2",
    "x": 4,
    "y": 8
  },
  {
    "id": "spyder_leather_town",
    "x": 17,
    "y": 19
  },
  {
    "id": "spyder_mansion_basement",
    "x": 6,
    "y": 20
  },
  {
    "id": "spyder_mansion_top",
    "x": 1,
    "y": 16
  },
  {
    "id": "spyder_nimrod_bottom",
    "x": 16,
    "y": 19
  },
  {
    "id": "spyder_nimrod_middle",
    "x": 15,
    "y": 18
  },
  {
    "id": "spyder_nimrod_room",
    "x": 8,
    "y": 6
  },
  {
    "id": "spyder_nimrod_top",
    "x": 0,
    "y": 17
  },
  {
    "id": "spyder_omnichannel1",
    "x": 2,
    "y": 11
  },
  {
    "id": "spyder_omnichannel2",
    "x": 1,
    "y": 12
  },
  {
    "id": "spyder_omnichannel3",
    "x": 1,
    "y": 12
  },
  {
    "id": "spyder_omnichannel4",
    "x": 1,
    "y": 12
  },
  {
    "id": "spyder_paper_daycare",
    "x": 0,
    "y": 3
  },
  {
    "id": "spyder_paper_manor",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_paper_rival_bedroom",
    "x": 1,
    "y": 3
  },
  {
    "id": "spyder_paper_rival_downstairs",
    "x": 7,
    "y": 9
  },
  {
    "id": "spyder_paper_rival_office",
    "x": 5,
    "y": 3
  },
  {
    "id": "spyder_paper_scoop",
    "x": 4,
    "y": 8
  },
  {
    "id": "spyder_paper_town",
    "x": 4,
    "y": 13
  },
  {
    "id": "spyder_radiotower",
    "x": 2,
    "y": 17
  },
  {
    "id": "spyder_scoop1",
    "x": 19,
    "y": 3
  },
  {
    "id": "spyder_scoop2",
    "x": 7,
    "y": 4
  },
  {
    "id": "spyder_scoop3",
    "x": 5,
    "y": 3
  },
  {
    "id": "spyder_scoop4",
    "x": 9,
    "y": 20
  },
  {
    "id": "spyder_test_map",
    "x": 2,
    "y": 2
  },
  {
    "id": "spyder_timber_cafe",
    "x": 8,
    "y": 10
  },
  {
    "id": "spyder_timber_center",
    "x": 6,
    "y": 9
  },
  {
    "id": "spyder_timber_house",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_timber_scoop",
    "x": 5,
    "y": 9
  },
  {
    "id": "spyder_timber_town",
    "x": 8,
    "y": 21
  },
  {
    "id": "spyder_timber_walledgarden1",
    "x": 7,
    "y": 3
  },
  {
    "id": "spyder_timber_walledgarden2",
    "x": 7,
    "y": 18
  },
  {
    "id": "spyder_wayfarer_inn1",
    "x": 9,
    "y": 6
  },
  {
    "id": "spyder_wayfarer_inn2",
    "x": 5,
    "y": 2
  },
  {
    "id": "start_tuxemon",
    "x": 1,
    "y": 0
  },
  {
    "id": "taba_ba_br_1",
    "x": 12,
    "y": 7
  },
  {
    "id": "taba_ba_br_2",
    "x": 7,
    "y": 1
  },
  {
    "id": "taba_ba_br_3",
    "x": 1,
    "y": 3
  },
  {
    "id": "taba_ba_br_4",
    "x": 4,
    "y": 1
  },
  {
    "id": "taba_ba_br_master",
    "x": 1,
    "y": 0
  },
  {
    "id": "taba_ba_br_master_foyer",
    "x": 2,
    "y": 15
  },
  {
    "id": "taba_ba_foyer",
    "x": 2,
    "y": 8
  },
  {
    "id": "taba_ba_main",
    "x": 1,
    "y": 13
  },
  {
    "id": "taba_ba_passageway_1",
    "x": 1,
    "y": 16
  },
  {
    "id": "taba_ba_passageway_2",
    "x": 14,
    "y": 17
  },
  {
    "id": "taba_ba_passageway_3",
    "x": 9,
    "y": 1
  },
  {
    "id": "taba_ba_passageway_4",
    "x": 3,
    "y": 18
  },
  {
    "id": "taba_ba_stairwell_1",
    "x": 1,
    "y": 8
  },
  {
    "id": "taba_ba_stairwell_2",
    "x": 8,
    "y": 1
  },
  {
    "id": "taba_house1",
    "x": 7,
    "y": 5
  },
  {
    "id": "taba_house2",
    "x": 5,
    "y": 2
  },
  {
    "id": "taba_house2_upstairs",
    "x": 7,
    "y": 2
  },
  {
    "id": "taba_house3",
    "x": 7,
    "y": 2
  },
  {
    "id": "taba_house3_upstairs",
    "x": 7,
    "y": 2
  },
  {
    "id": "taba_house4",
    "x": 7,
    "y": 5
  },
  {
    "id": "taba_town",
    "x": 40,
    "y": 4
  },
  {
    "id": "tabathas",
    "x": 6,
    "y": 9
  },
  {
    "id": "test_npcs",
    "x": 13,
    "y": 1
  },
  {
    "id": "timber_town",
    "x": 10,
    "y": 23
  },
  {
    "id": "tt_forest_route1",
    "x": 8,
    "y": 38
  },
  {
    "id": "tt_paper_town",
    "x": 14,
    "y": 4
  },
  {
    "id": "tt_searoute1",
    "x": 38,
    "y": 0
  },
  {
    "id": "tunnel",
    "x": 7,
    "y": 3
  },
  {
    "id": "tunnel_below",
    "x": 13,
    "y": 25
  },
  {
    "id": "tuxe_mart_taba",
    "x": 6,
    "y": 9
  },
  {
    "id": "water_cathedral",
    "x": 23,
    "y": 58
  },
  {
    "id": "water_end_of_desert",
    "x": 11,
    "y": 32
  },
  {
    "id": "water_lower_village",
    "x": 34,
    "y": 22
  },
  {
    "id": "water_outskirts",
    "x": 28,
    "y": 4
  },
  {
    "id": "water_river_village",
    "x": 17,
    "y": 28
  },
  {
    "id": "water_route_grass",
    "x": 23,
    "y": 48
  },
  {
    "id": "water_route_ice",
    "x": 23,
    "y": 20
  },
  {
    "id": "water_snow_village",
    "x": 11,
    "y": 28
  },
  {
    "id": "water_underwater",
    "x": 42,
    "y": 38
  },
  {
    "id": "water_volcano_path",
    "x": 10,
    "y": 10
  },
  {
    "id": "water_volcano_village",
    "x": 1,
    "y": 26
  },
  {
    "id": "wayfarer_inn1",
    "x": 11,
    "y": 10
  },
  {
    "id": "wayfarer_inn2",
    "x": 5,
    "y": 2
  },
  {
    "id": "witcher_route_7",
    "x": 0,
    "y": 11
  }
] as const;
