// AUTO-GENERATED by gen-assets.ts — do not edit.
// The chapter snapshots and the mainline tape live in the pak (entries
// below) and are read on demand when a chapter is first selected. The
// zh_CN index is empty when the build has no current Chinese tape.
import type { DemoChapterIndexEntry } from "../importer/demo-data.ts";

export const DEMO_TAPE_ENTRY = "demo/tape.bin";
export const DEMO_SNAPSHOTS_ENTRY = "demo/chapters.json";
export const DEMO_TAPE_ENTRY_ZH = "demo/tape.zh_CN.bin";
export const DEMO_SNAPSHOTS_ENTRY_ZH = "demo/chapters.zh_CN.json";

export const DEMO_CHAPTER_INDEX: readonly DemoChapterIndexEntry[] = [
  {
    "id": "bedroom",
    "title": "Bedroom (new game)",
    "worldTraversal": "seamless-v1",
    "frame": 0,
    "suffixFrames": 206830,
    "timelineFrame": 0
  },
  {
    "id": "paper-town",
    "title": "Paper Town",
    "worldTraversal": "seamless-v1",
    "frame": 1387,
    "suffixFrames": 205443,
    "timelineFrame": 1387
  },
  {
    "id": "before-billie",
    "title": "Before the first Billie battle",
    "worldTraversal": "seamless-v1",
    "frame": 1912,
    "suffixFrames": 204918,
    "timelineFrame": 1912
  },
  {
    "id": "starter",
    "title": "Starter chosen",
    "worldTraversal": "seamless-v1",
    "frame": 3210,
    "suffixFrames": 203620,
    "timelineFrame": 3210
  },
  {
    "id": "route-1",
    "title": "Route 1",
    "worldTraversal": "seamless-v1",
    "frame": 3500,
    "suffixFrames": 203330,
    "timelineFrame": 3500
  },
  {
    "id": "cotton-town",
    "title": "Cotton Town",
    "worldTraversal": "seamless-v1",
    "frame": 5581,
    "suffixFrames": 201249,
    "timelineFrame": 5581
  },
  {
    "id": "city-park",
    "title": "City Park",
    "worldTraversal": "seamless-v1",
    "frame": 47245,
    "suffixFrames": 159585,
    "timelineFrame": 47245
  },
  {
    "id": "route-3-north",
    "title": "Route 3 north end",
    "worldTraversal": "seamless-v1",
    "frame": 115842,
    "suffixFrames": 90988,
    "timelineFrame": 115842
  },
  {
    "id": "flower-city",
    "title": "Flower City",
    "worldTraversal": "seamless-v1",
    "frame": 121034,
    "suffixFrames": 85796,
    "timelineFrame": 121034
  },
  {
    "id": "captain-returns",
    "title": "Captain's return",
    "worldTraversal": "seamless-v1",
    "frame": 128718,
    "suffixFrames": 78112,
    "timelineFrame": 128718
  },
  {
    "id": "candy-town",
    "title": "Candy Town",
    "worldTraversal": "seamless-v1",
    "frame": 172078,
    "suffixFrames": 34752,
    "timelineFrame": 172078
  },
  {
    "id": "greenwash-aardant",
    "title": "Greenwash (Aardant acquired)",
    "worldTraversal": "seamless-v1",
    "frame": 178679,
    "suffixFrames": 28151,
    "timelineFrame": 178679
  },
  {
    "id": "hospital-cure",
    "title": "Hospital cure",
    "worldTraversal": "seamless-v1",
    "frame": 180118,
    "suffixFrames": 26712,
    "timelineFrame": 180118
  },
  {
    "id": "omnichannel-open",
    "title": "Omnichannel passage opened",
    "worldTraversal": "seamless-v1",
    "frame": 187596,
    "suffixFrames": 19234,
    "timelineFrame": 187596
  },
  {
    "id": "radio-broadcast",
    "title": "Radio Tower broadcast",
    "worldTraversal": "seamless-v1",
    "frame": 193208,
    "suffixFrames": 13622,
    "timelineFrame": 193208
  },
  {
    "id": "kernel-briefing",
    "title": "Kernel quest briefing",
    "worldTraversal": "seamless-v1",
    "frame": 195079,
    "suffixFrames": 11751,
    "timelineFrame": 195079
  },
  {
    "id": "surfboard",
    "title": "Surfboard acquired",
    "worldTraversal": "seamless-v1",
    "frame": 196197,
    "suffixFrames": 10633,
    "timelineFrame": 196197
  },
  {
    "id": "route-b",
    "title": "Route B",
    "worldTraversal": "seamless-v1",
    "frame": 198344,
    "suffixFrames": 8486,
    "timelineFrame": 198344
  },
  {
    "id": "data-center",
    "title": "Data Center",
    "worldTraversal": "seamless-v1",
    "frame": 201836,
    "suffixFrames": 4994,
    "timelineFrame": 201836
  },
  {
    "id": "kernel-defeated",
    "title": "Kernel quest complete",
    "worldTraversal": "seamless-v1",
    "frame": 206819,
    "suffixFrames": 11,
    "timelineFrame": 206819
  }
];

export const DEMO_CHAPTER_INDEX_ZH: readonly DemoChapterIndexEntry[] = [
  {
    "id": "bedroom",
    "title": "房间（新游戏）",
    "worldTraversal": "seamless-v1",
    "frame": 0,
    "suffixFrames": 206830,
    "timelineFrame": 0
  },
  {
    "id": "paper-town",
    "title": "方絮镇",
    "worldTraversal": "seamless-v1",
    "frame": 1387,
    "suffixFrames": 205443,
    "timelineFrame": 1387
  },
  {
    "id": "before-billie",
    "title": "首次对战比莉之前",
    "worldTraversal": "seamless-v1",
    "frame": 1912,
    "suffixFrames": 204918,
    "timelineFrame": 1912
  },
  {
    "id": "starter",
    "title": "选定初始精灵",
    "worldTraversal": "seamless-v1",
    "frame": 3210,
    "suffixFrames": 203620,
    "timelineFrame": 3210
  },
  {
    "id": "route-1",
    "title": "路线1",
    "worldTraversal": "seamless-v1",
    "frame": 3500,
    "suffixFrames": 203330,
    "timelineFrame": 3500
  },
  {
    "id": "cotton-town",
    "title": "暖棉镇",
    "worldTraversal": "seamless-v1",
    "frame": 5581,
    "suffixFrames": 201249,
    "timelineFrame": 5581
  },
  {
    "id": "city-park",
    "title": "城市公园",
    "worldTraversal": "seamless-v1",
    "frame": 47245,
    "suffixFrames": 159585,
    "timelineFrame": 47245
  },
  {
    "id": "route-3-north",
    "title": "路线3北端",
    "worldTraversal": "seamless-v1",
    "frame": 115842,
    "suffixFrames": 90988,
    "timelineFrame": 115842
  },
  {
    "id": "flower-city",
    "title": "彩花城",
    "worldTraversal": "seamless-v1",
    "frame": 121034,
    "suffixFrames": 85796,
    "timelineFrame": 121034
  },
  {
    "id": "captain-returns",
    "title": "船长归来",
    "worldTraversal": "seamless-v1",
    "frame": 128718,
    "suffixFrames": 78112,
    "timelineFrame": 128718
  },
  {
    "id": "candy-town",
    "title": "甜饴镇",
    "worldTraversal": "seamless-v1",
    "frame": 172078,
    "suffixFrames": 34752,
    "timelineFrame": 172078
  },
  {
    "id": "greenwash-aardant",
    "title": "格林沃什（获得阿尔丹特）",
    "worldTraversal": "seamless-v1",
    "frame": 178679,
    "suffixFrames": 28151,
    "timelineFrame": 178679
  },
  {
    "id": "hospital-cure",
    "title": "医院治疗",
    "worldTraversal": "seamless-v1",
    "frame": 180118,
    "suffixFrames": 26712,
    "timelineFrame": 180118
  },
  {
    "id": "omnichannel-open",
    "title": "全能公司通道开启",
    "worldTraversal": "seamless-v1",
    "frame": 187596,
    "suffixFrames": 19234,
    "timelineFrame": 187596
  },
  {
    "id": "radio-broadcast",
    "title": "电台广播",
    "worldTraversal": "seamless-v1",
    "frame": 193208,
    "suffixFrames": 13622,
    "timelineFrame": 193208
  },
  {
    "id": "kernel-briefing",
    "title": "科内尔任务简报",
    "worldTraversal": "seamless-v1",
    "frame": 195079,
    "suffixFrames": 11751,
    "timelineFrame": 195079
  },
  {
    "id": "surfboard",
    "title": "获得冲浪板",
    "worldTraversal": "seamless-v1",
    "frame": 196197,
    "suffixFrames": 10633,
    "timelineFrame": 196197
  },
  {
    "id": "route-b",
    "title": "路线B",
    "worldTraversal": "seamless-v1",
    "frame": 198344,
    "suffixFrames": 8486,
    "timelineFrame": 198344
  },
  {
    "id": "data-center",
    "title": "数据中心",
    "worldTraversal": "seamless-v1",
    "frame": 201836,
    "suffixFrames": 4994,
    "timelineFrame": 201836
  },
  {
    "id": "kernel-defeated",
    "title": "科内尔任务完成",
    "worldTraversal": "seamless-v1",
    "frame": 206819,
    "suffixFrames": 11,
    "timelineFrame": 206819
  }
];

export const DEMO_WARP_SPAWNS = [
  {
    "id": "37707_tower",
    "x": 12,
    "y": 21
  },
  {
    "id": "37707_town",
    "x": 24,
    "y": 6
  },
  {
    "id": "37707_town_missing",
    "x": 24,
    "y": 6
  },
  {
    "id": "azure_town",
    "x": 41,
    "y": 23
  },
  {
    "id": "azure_town_hall",
    "x": 20,
    "y": 18
  },
  {
    "id": "bedroom_test",
    "x": 8,
    "y": 2
  },
  {
    "id": "buddha_mountain",
    "x": 3,
    "y": 89
  },
  {
    "id": "candy_town",
    "x": 7,
    "y": 38
  },
  {
    "id": "city1_mart_junkyard",
    "x": 11,
    "y": 4
  },
  {
    "id": "citypark",
    "x": 36,
    "y": 4
  },
  {
    "id": "citypark_house1",
    "x": 6,
    "y": 6
  },
  {
    "id": "classic_aerolume_city",
    "x": 0,
    "y": 15
  },
  {
    "id": "classic_gym_astra",
    "x": 10,
    "y": 18
  },
  {
    "id": "classic_gym_bravion",
    "x": 10,
    "y": 18
  },
  {
    "id": "classic_gym_ferrum",
    "x": 2,
    "y": 0
  },
  {
    "id": "classic_gym_granite",
    "x": 10,
    "y": 18
  },
  {
    "id": "classic_gym_marin",
    "x": 10,
    "y": 18
  },
  {
    "id": "classic_gym_mila",
    "x": 10,
    "y": 18
  },
  {
    "id": "classic_gym_orion",
    "x": 2,
    "y": 0
  },
  {
    "id": "classic_gym_pyra",
    "x": 10,
    "y": 18
  },
  {
    "id": "classic_gym_shade",
    "x": 2,
    "y": 0
  },
  {
    "id": "classic_gym_sylva",
    "x": 2,
    "y": 0
  },
  {
    "id": "classic_gym_voltessa",
    "x": 10,
    "y": 18
  },
  {
    "id": "classic_gym_vyre",
    "x": 2,
    "y": 0
  },
  {
    "id": "classic_gym_zephra",
    "x": 2,
    "y": 0
  },
  {
    "id": "classic_hearthrock_city",
    "x": 23,
    "y": 14
  },
  {
    "id": "classic_route_1",
    "x": 32,
    "y": 18
  },
  {
    "id": "classic_route_2",
    "x": 0,
    "y": 1
  },
  {
    "id": "classic_route_3",
    "x": 20,
    "y": 19
  },
  {
    "id": "classic_route_5",
    "x": 39,
    "y": 15
  },
  {
    "id": "classic_route_6",
    "x": 1,
    "y": 1
  },
  {
    "id": "classic_route_7",
    "x": 35,
    "y": 1
  },
  {
    "id": "classic_route_8",
    "x": 1,
    "y": 15
  },
  {
    "id": "classic_steamshore_city",
    "x": 31,
    "y": 5
  },
  {
    "id": "classic_stormpeak_city",
    "x": 35,
    "y": 4
  },
  {
    "id": "classic_thornwood_city",
    "x": 1,
    "y": 16
  },
  {
    "id": "classic_umbrastar_city",
    "x": 0,
    "y": 15
  },
  {
    "id": "classic_valorhold_city",
    "x": 27,
    "y": 13
  },
  {
    "id": "cotton_cafe",
    "x": 1,
    "y": 10
  },
  {
    "id": "cotton_cafe_basement",
    "x": 1,
    "y": 10
  },
  {
    "id": "cotton_cathedral",
    "x": 6,
    "y": 9
  },
  {
    "id": "cotton_daycare",
    "x": 2,
    "y": 7
  },
  {
    "id": "cotton_misa_house",
    "x": 4,
    "y": 2
  },
  {
    "id": "cotton_misa_house_upstairs",
    "x": 8,
    "y": 2
  },
  {
    "id": "cotton_scoop",
    "x": 5,
    "y": 9
  },
  {
    "id": "cotton_town",
    "x": 10,
    "y": 17
  },
  {
    "id": "cotton_underground",
    "x": 10,
    "y": 16
  },
  {
    "id": "dojo1",
    "x": 11,
    "y": 5
  },
  {
    "id": "dojo2",
    "x": 10,
    "y": 9
  },
  {
    "id": "dojo3",
    "x": 10,
    "y": 9
  },
  {
    "id": "downstairs_test",
    "x": 0,
    "y": 2
  },
  {
    "id": "dragonscave",
    "x": 12,
    "y": 38
  },
  {
    "id": "dryadsgrove",
    "x": 1,
    "y": 7
  },
  {
    "id": "eclipse_crystal_bank1",
    "x": 1,
    "y": 10
  },
  {
    "id": "eclipse_crystal_bank2",
    "x": 2,
    "y": 15
  },
  {
    "id": "eclipse_crystal_bank3",
    "x": 2,
    "y": 12
  },
  {
    "id": "eclipse_crystal_center",
    "x": 6,
    "y": 7
  },
  {
    "id": "eclipse_crystal_town",
    "x": 6,
    "y": 8
  },
  {
    "id": "eclipse_crystal_town_cafe",
    "x": 8,
    "y": 10
  },
  {
    "id": "eclipse_crystal_town_house",
    "x": 4,
    "y": 6
  },
  {
    "id": "eclipse_lion_mountain_high",
    "x": 39,
    "y": 13
  },
  {
    "id": "eclipse_lion_mountain_low",
    "x": 0,
    "y": 9
  },
  {
    "id": "eclipse_lion_mountain_middle",
    "x": 2,
    "y": 1
  },
  {
    "id": "eclipse_obsidian_center",
    "x": 6,
    "y": 9
  },
  {
    "id": "eclipse_obsidian_town",
    "x": 16,
    "y": 9
  },
  {
    "id": "eclipse_obsidian_town_house",
    "x": 4,
    "y": 6
  },
  {
    "id": "eclipse_park",
    "x": 38,
    "y": 13
  },
  {
    "id": "eclipse_park_cabin",
    "x": 6,
    "y": 4
  },
  {
    "id": "eclipse_park_cave",
    "x": 32,
    "y": 11
  },
  {
    "id": "eclipse_park_entrance",
    "x": 4,
    "y": 3
  },
  {
    "id": "eclipse_park_south",
    "x": 6,
    "y": 35
  },
  {
    "id": "eclipse_route7",
    "x": 35,
    "y": 1
  },
  {
    "id": "eclipse_routef",
    "x": 24,
    "y": 0
  },
  {
    "id": "eclipse_routeg",
    "x": 24,
    "y": 38
  },
  {
    "id": "eclipse_routeh",
    "x": 23,
    "y": 39
  },
  {
    "id": "eclipse_routei",
    "x": 26,
    "y": 10
  },
  {
    "id": "flower_city",
    "x": 3,
    "y": 18
  },
  {
    "id": "gadget_store1",
    "x": 0,
    "y": 3
  },
  {
    "id": "gaming_hall",
    "x": 1,
    "y": 0
  },
  {
    "id": "healing_center",
    "x": 6,
    "y": 9
  },
  {
    "id": "leather_scoop",
    "x": 5,
    "y": 9
  },
  {
    "id": "leather_shaft1",
    "x": 12,
    "y": 13
  },
  {
    "id": "leather_shaft2",
    "x": 4,
    "y": 8
  },
  {
    "id": "leather_town",
    "x": 24,
    "y": 10
  },
  {
    "id": "manhattan_beach",
    "x": 27,
    "y": 38
  },
  {
    "id": "mansion",
    "x": 2,
    "y": 15
  },
  {
    "id": "mansion_basement",
    "x": 7,
    "y": 20
  },
  {
    "id": "mansion_top",
    "x": 1,
    "y": 16
  },
  {
    "id": "maple_bedroom",
    "x": 8,
    "y": 2
  },
  {
    "id": "maple_house",
    "x": 11,
    "y": 2
  },
  {
    "id": "omnichannel0",
    "x": 1,
    "y": 5
  },
  {
    "id": "omnichannel1",
    "x": 1,
    "y": 3
  },
  {
    "id": "omnichannel2",
    "x": 1,
    "y": 12
  },
  {
    "id": "omnichannel3",
    "x": 1,
    "y": 12
  },
  {
    "id": "omnichannel4",
    "x": 1,
    "y": 12
  },
  {
    "id": "player_house_bedroom",
    "x": 1,
    "y": 3
  },
  {
    "id": "player_house_downstairs",
    "x": 1,
    "y": 2
  },
  {
    "id": "professor_lab",
    "x": 6,
    "y": 16
  },
  {
    "id": "route1",
    "x": 18,
    "y": 6
  },
  {
    "id": "route1_sanglorian",
    "x": 10,
    "y": 1
  },
  {
    "id": "route2",
    "x": 11,
    "y": 1
  },
  {
    "id": "route3",
    "x": 30,
    "y": 38
  },
  {
    "id": "route4",
    "x": 18,
    "y": 3
  },
  {
    "id": "route5",
    "x": 1,
    "y": 15
  },
  {
    "id": "route6",
    "x": 7,
    "y": 1
  },
  {
    "id": "routea",
    "x": 6,
    "y": 13
  },
  {
    "id": "routec",
    "x": 38,
    "y": 5
  },
  {
    "id": "rubberduck_cave_01",
    "x": 49,
    "y": 14
  },
  {
    "id": "rubberduck_city_01",
    "x": 12,
    "y": 12
  },
  {
    "id": "rubberduck_route_01",
    "x": 37,
    "y": 10
  },
  {
    "id": "russell_practice_1",
    "x": 1,
    "y": 0
  },
  {
    "id": "scoop1",
    "x": 19,
    "y": 3
  },
  {
    "id": "scoop2",
    "x": 7,
    "y": 4
  },
  {
    "id": "scoop3",
    "x": 5,
    "y": 3
  },
  {
    "id": "scoop4",
    "x": 9,
    "y": 20
  },
  {
    "id": "sphalian_center",
    "x": 6,
    "y": 9
  },
  {
    "id": "sphalian_town",
    "x": 21,
    "y": 14
  },
  {
    "id": "sphalian_town_house",
    "x": 5,
    "y": 6
  },
  {
    "id": "spyder_bedroom",
    "x": 8,
    "y": 2
  },
  {
    "id": "spyder_brideswood",
    "x": 1,
    "y": 27
  },
  {
    "id": "spyder_candy_cafe",
    "x": 4,
    "y": 7
  },
  {
    "id": "spyder_candy_center",
    "x": 14,
    "y": 5
  },
  {
    "id": "spyder_candy_hospital1",
    "x": 7,
    "y": 15
  },
  {
    "id": "spyder_candy_hospital2",
    "x": 11,
    "y": 15
  },
  {
    "id": "spyder_candy_hospital3",
    "x": 5,
    "y": 18
  },
  {
    "id": "spyder_candy_house1",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_candy_house2",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_candy_house3",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_candy_inn1",
    "x": 3,
    "y": 2
  },
  {
    "id": "spyder_candy_inn2",
    "x": 5,
    "y": 2
  },
  {
    "id": "spyder_candy_port",
    "x": 22,
    "y": 5
  },
  {
    "id": "spyder_candy_scoop",
    "x": 5,
    "y": 9
  },
  {
    "id": "spyder_candy_town",
    "x": 4,
    "y": 19
  },
  {
    "id": "spyder_citypark_house1",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_cotton_artshop",
    "x": 2,
    "y": 8
  },
  {
    "id": "spyder_cotton_cafe",
    "x": 8,
    "y": 10
  },
  {
    "id": "spyder_cotton_house1",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_cotton_house2",
    "x": 5,
    "y": 2
  },
  {
    "id": "spyder_cotton_scoop",
    "x": 5,
    "y": 9
  },
  {
    "id": "spyder_cotton_town",
    "x": 16,
    "y": 17
  },
  {
    "id": "spyder_cotton_tunnel",
    "x": 35,
    "y": 3
  },
  {
    "id": "spyder_datacenter",
    "x": 2,
    "y": 18
  },
  {
    "id": "spyder_diamond_hill",
    "x": 18,
    "y": 51
  },
  {
    "id": "spyder_dojo1",
    "x": 11,
    "y": 5
  },
  {
    "id": "spyder_dojo2",
    "x": 10,
    "y": 8
  },
  {
    "id": "spyder_dojo3",
    "x": 10,
    "y": 8
  },
  {
    "id": "spyder_dojo4",
    "x": 10,
    "y": 8
  },
  {
    "id": "spyder_downstairs",
    "x": 0,
    "y": 2
  },
  {
    "id": "spyder_flower_center",
    "x": 6,
    "y": 9
  },
  {
    "id": "spyder_flower_city",
    "x": 17,
    "y": 30
  },
  {
    "id": "spyder_flower_house1",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_flower_house2",
    "x": 2,
    "y": 7
  },
  {
    "id": "spyder_flower_petshop",
    "x": 1,
    "y": 6
  },
  {
    "id": "spyder_flower_scoop",
    "x": 5,
    "y": 9
  },
  {
    "id": "spyder_greenwash",
    "x": 14,
    "y": 19
  },
  {
    "id": "spyder_greenwash_greenhouse",
    "x": 1,
    "y": 7
  },
  {
    "id": "spyder_greenwash_level2",
    "x": 1,
    "y": 4
  },
  {
    "id": "spyder_greenwash_level3",
    "x": 13,
    "y": 2
  },
  {
    "id": "spyder_healing_center",
    "x": 6,
    "y": 9
  },
  {
    "id": "spyder_leather_center",
    "x": 6,
    "y": 9
  },
  {
    "id": "spyder_leather_gym",
    "x": 1,
    "y": 9
  },
  {
    "id": "spyder_leather_house1",
    "x": 4,
    "y": 6
  },
  {
    "id": "spyder_leather_house2",
    "x": 2,
    "y": 6
  },
  {
    "id": "spyder_leather_museum",
    "x": 0,
    "y": 10
  },
  {
    "id": "spyder_leather_scoop",
    "x": 5,
    "y": 9
  },
  {
    "id": "spyder_leather_shaft1",
    "x": 12,
    "y": 13
  },
  {
    "id": "spyder_leather_shaft2",
    "x": 4,
    "y": 8
  },
  {
    "id": "spyder_leather_town",
    "x": 17,
    "y": 19
  },
  {
    "id": "spyder_mansion_basement",
    "x": 6,
    "y": 20
  },
  {
    "id": "spyder_mansion_top",
    "x": 1,
    "y": 16
  },
  {
    "id": "spyder_nimrod_bottom",
    "x": 16,
    "y": 19
  },
  {
    "id": "spyder_nimrod_middle",
    "x": 15,
    "y": 18
  },
  {
    "id": "spyder_nimrod_room",
    "x": 8,
    "y": 6
  },
  {
    "id": "spyder_nimrod_top",
    "x": 0,
    "y": 17
  },
  {
    "id": "spyder_omnichannel1",
    "x": 2,
    "y": 11
  },
  {
    "id": "spyder_omnichannel2",
    "x": 1,
    "y": 12
  },
  {
    "id": "spyder_omnichannel3",
    "x": 1,
    "y": 12
  },
  {
    "id": "spyder_omnichannel4",
    "x": 1,
    "y": 12
  },
  {
    "id": "spyder_paper_daycare",
    "x": 0,
    "y": 3
  },
  {
    "id": "spyder_paper_manor",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_paper_rival_bedroom",
    "x": 1,
    "y": 3
  },
  {
    "id": "spyder_paper_rival_downstairs",
    "x": 7,
    "y": 9
  },
  {
    "id": "spyder_paper_rival_office",
    "x": 5,
    "y": 3
  },
  {
    "id": "spyder_paper_scoop",
    "x": 4,
    "y": 8
  },
  {
    "id": "spyder_paper_town",
    "x": 4,
    "y": 13
  },
  {
    "id": "spyder_radiotower",
    "x": 2,
    "y": 17
  },
  {
    "id": "spyder_scoop1",
    "x": 19,
    "y": 3
  },
  {
    "id": "spyder_scoop2",
    "x": 7,
    "y": 4
  },
  {
    "id": "spyder_scoop3",
    "x": 5,
    "y": 3
  },
  {
    "id": "spyder_scoop4",
    "x": 9,
    "y": 20
  },
  {
    "id": "spyder_test_map",
    "x": 2,
    "y": 2
  },
  {
    "id": "spyder_timber_cafe",
    "x": 8,
    "y": 10
  },
  {
    "id": "spyder_timber_center",
    "x": 6,
    "y": 9
  },
  {
    "id": "spyder_timber_house",
    "x": 6,
    "y": 6
  },
  {
    "id": "spyder_timber_scoop",
    "x": 5,
    "y": 9
  },
  {
    "id": "spyder_timber_town",
    "x": 8,
    "y": 21
  },
  {
    "id": "spyder_timber_walledgarden1",
    "x": 7,
    "y": 3
  },
  {
    "id": "spyder_timber_walledgarden2",
    "x": 7,
    "y": 18
  },
  {
    "id": "spyder_wayfarer_inn1",
    "x": 9,
    "y": 6
  },
  {
    "id": "spyder_wayfarer_inn2",
    "x": 5,
    "y": 2
  },
  {
    "id": "start_tuxemon",
    "x": 1,
    "y": 0
  },
  {
    "id": "taba_ba_br_1",
    "x": 12,
    "y": 7
  },
  {
    "id": "taba_ba_br_2",
    "x": 7,
    "y": 1
  },
  {
    "id": "taba_ba_br_3",
    "x": 1,
    "y": 3
  },
  {
    "id": "taba_ba_br_4",
    "x": 4,
    "y": 1
  },
  {
    "id": "taba_ba_br_master",
    "x": 1,
    "y": 0
  },
  {
    "id": "taba_ba_br_master_foyer",
    "x": 2,
    "y": 15
  },
  {
    "id": "taba_ba_foyer",
    "x": 2,
    "y": 8
  },
  {
    "id": "taba_ba_main",
    "x": 1,
    "y": 13
  },
  {
    "id": "taba_ba_passageway_1",
    "x": 1,
    "y": 16
  },
  {
    "id": "taba_ba_passageway_2",
    "x": 14,
    "y": 17
  },
  {
    "id": "taba_ba_passageway_3",
    "x": 9,
    "y": 1
  },
  {
    "id": "taba_ba_passageway_4",
    "x": 3,
    "y": 18
  },
  {
    "id": "taba_ba_stairwell_1",
    "x": 1,
    "y": 8
  },
  {
    "id": "taba_ba_stairwell_2",
    "x": 8,
    "y": 1
  },
  {
    "id": "taba_house1",
    "x": 7,
    "y": 5
  },
  {
    "id": "taba_house2",
    "x": 5,
    "y": 2
  },
  {
    "id": "taba_house2_upstairs",
    "x": 7,
    "y": 2
  },
  {
    "id": "taba_house3",
    "x": 7,
    "y": 2
  },
  {
    "id": "taba_house3_upstairs",
    "x": 7,
    "y": 2
  },
  {
    "id": "taba_house4",
    "x": 7,
    "y": 5
  },
  {
    "id": "taba_town",
    "x": 40,
    "y": 4
  },
  {
    "id": "tabathas",
    "x": 6,
    "y": 9
  },
  {
    "id": "test_npcs",
    "x": 13,
    "y": 1
  },
  {
    "id": "timber_town",
    "x": 10,
    "y": 23
  },
  {
    "id": "tt_forest_route1",
    "x": 8,
    "y": 38
  },
  {
    "id": "tt_paper_town",
    "x": 14,
    "y": 4
  },
  {
    "id": "tt_searoute1",
    "x": 38,
    "y": 0
  },
  {
    "id": "tunnel",
    "x": 7,
    "y": 3
  },
  {
    "id": "tunnel_below",
    "x": 13,
    "y": 25
  },
  {
    "id": "tuxe_mart_taba",
    "x": 6,
    "y": 9
  },
  {
    "id": "water_cathedral",
    "x": 23,
    "y": 58
  },
  {
    "id": "water_end_of_desert",
    "x": 11,
    "y": 32
  },
  {
    "id": "water_lower_village",
    "x": 34,
    "y": 22
  },
  {
    "id": "water_outskirts",
    "x": 28,
    "y": 4
  },
  {
    "id": "water_river_village",
    "x": 17,
    "y": 28
  },
  {
    "id": "water_route_grass",
    "x": 23,
    "y": 48
  },
  {
    "id": "water_route_ice",
    "x": 23,
    "y": 20
  },
  {
    "id": "water_snow_village",
    "x": 11,
    "y": 28
  },
  {
    "id": "water_underwater",
    "x": 42,
    "y": 38
  },
  {
    "id": "water_volcano_path",
    "x": 10,
    "y": 10
  },
  {
    "id": "water_volcano_village",
    "x": 1,
    "y": 26
  },
  {
    "id": "wayfarer_inn1",
    "x": 11,
    "y": 10
  },
  {
    "id": "wayfarer_inn2",
    "x": 5,
    "y": 2
  },
  {
    "id": "witcher_route_7",
    "x": 0,
    "y": 11
  }
] as const;
