// AUTO-GENERATED by gen-assets.ts — do not edit.
import type { GameAssets } from "../vendor/pocket-rpgkit/src/ui/game-assets.ts";
import type { PlayerFrames } from "../vendor/pocket-rpgkit/src/ui/PlayerSprite.tsx";
import { TERRAIN_ORDER, TERRAIN_WORLD } from "./terrain-assets.ts";

export const PLAYER: PlayerFrames = {
  "idle": [
    "assets/characters/player-adventurer-idle-0.png",
    "assets/characters/player-adventurer-idle-1.png",
    "assets/characters/player-adventurer-idle-2.png",
    "assets/characters/player-adventurer-idle-3.png"
  ],
  "walkL": [
    "assets/characters/player-adventurer-walk-l-0.png",
    "assets/characters/player-adventurer-walk-l-1.png",
    "assets/characters/player-adventurer-walk-l-2.png",
    "assets/characters/player-adventurer-walk-l-3.png"
  ],
  "walkR": [
    "assets/characters/player-adventurer-walk-r-0.png",
    "assets/characters/player-adventurer-walk-r-1.png",
    "assets/characters/player-adventurer-walk-r-2.png",
    "assets/characters/player-adventurer-walk-r-3.png"
  ]
};

export const ANIMATED_INDEX: readonly { id: string; entry: string }[] = [
  {
    "id": "37707_town",
    "entry": "animated/37707_town.json"
  },
  {
    "id": "37707_town_missing",
    "entry": "animated/37707_town_missing.json"
  },
  {
    "id": "candy_town",
    "entry": "animated/candy_town.json"
  },
  {
    "id": "citypark",
    "entry": "animated/citypark.json"
  },
  {
    "id": "classic_route_1",
    "entry": "animated/classic_route_1.json"
  },
  {
    "id": "cotton_town",
    "entry": "animated/cotton_town.json"
  },
  {
    "id": "eclipse_crystal_town",
    "entry": "animated/eclipse_crystal_town.json"
  },
  {
    "id": "eclipse_lion_mountain_high",
    "entry": "animated/eclipse_lion_mountain_high.json"
  },
  {
    "id": "eclipse_lion_mountain_low",
    "entry": "animated/eclipse_lion_mountain_low.json"
  },
  {
    "id": "eclipse_lion_mountain_middle",
    "entry": "animated/eclipse_lion_mountain_middle.json"
  },
  {
    "id": "eclipse_park",
    "entry": "animated/eclipse_park.json"
  },
  {
    "id": "eclipse_route7",
    "entry": "animated/eclipse_route7.json"
  },
  {
    "id": "eclipse_routeg",
    "entry": "animated/eclipse_routeg.json"
  },
  {
    "id": "flower_city",
    "entry": "animated/flower_city.json"
  },
  {
    "id": "leather_town",
    "entry": "animated/leather_town.json"
  },
  {
    "id": "manhattan_beach",
    "entry": "animated/manhattan_beach.json"
  },
  {
    "id": "route1",
    "entry": "animated/route1.json"
  },
  {
    "id": "route1_sanglorian",
    "entry": "animated/route1_sanglorian.json"
  },
  {
    "id": "route3",
    "entry": "animated/route3.json"
  },
  {
    "id": "route4",
    "entry": "animated/route4.json"
  },
  {
    "id": "routea",
    "entry": "animated/routea.json"
  },
  {
    "id": "rubberduck_city_01",
    "entry": "animated/rubberduck_city_01.json"
  },
  {
    "id": "spyder_candy_port",
    "entry": "animated/spyder_candy_port.json"
  },
  {
    "id": "spyder_candy_town",
    "entry": "animated/spyder_candy_town.json"
  },
  {
    "id": "spyder_citypark",
    "entry": "animated/spyder_citypark.json"
  },
  {
    "id": "spyder_cotton_town",
    "entry": "animated/spyder_cotton_town.json"
  },
  {
    "id": "spyder_diamond_hill",
    "entry": "animated/spyder_diamond_hill.json"
  },
  {
    "id": "spyder_flower_city",
    "entry": "animated/spyder_flower_city.json"
  },
  {
    "id": "spyder_leather_town",
    "entry": "animated/spyder_leather_town.json"
  },
  {
    "id": "spyder_paper_town",
    "entry": "animated/spyder_paper_town.json"
  },
  {
    "id": "spyder_route1",
    "entry": "animated/spyder_route1.json"
  },
  {
    "id": "spyder_route2",
    "entry": "animated/spyder_route2.json"
  },
  {
    "id": "spyder_route3",
    "entry": "animated/spyder_route3.json"
  },
  {
    "id": "spyder_route4",
    "entry": "animated/spyder_route4.json"
  },
  {
    "id": "spyder_routea",
    "entry": "animated/spyder_routea.json"
  },
  {
    "id": "spyder_routeb",
    "entry": "animated/spyder_routeb.json"
  },
  {
    "id": "spyder_routee",
    "entry": "animated/spyder_routee.json"
  },
  {
    "id": "spyder_timber_town",
    "entry": "animated/spyder_timber_town.json"
  },
  {
    "id": "taba_town",
    "entry": "animated/taba_town.json"
  },
  {
    "id": "timber_town",
    "entry": "animated/timber_town.json"
  },
  {
    "id": "tt_forest_route1",
    "entry": "animated/tt_forest_route1.json"
  },
  {
    "id": "tt_searoute1",
    "entry": "animated/tt_searoute1.json"
  },
  {
    "id": "water_end_of_desert",
    "entry": "animated/water_end_of_desert.json"
  },
  {
    "id": "water_lower_village",
    "entry": "animated/water_lower_village.json"
  },
  {
    "id": "water_outskirts",
    "entry": "animated/water_outskirts.json"
  },
  {
    "id": "water_river_village",
    "entry": "animated/water_river_village.json"
  },
  {
    "id": "water_route_grass",
    "entry": "animated/water_route_grass.json"
  },
  {
    "id": "water_volcano_path",
    "entry": "animated/water_volcano_path.json"
  }
] as const;

export const NPC_SRC_INDEX: readonly { id: string; entry: string }[] = [
  {
    "id": "adventurer",
    "entry": "npc-src/adventurer.json"
  },
  {
    "id": "adventurerblack",
    "entry": "npc-src/adventurerblack.json"
  },
  {
    "id": "brownheroine_brown",
    "entry": "npc-src/brownheroine_brown.json"
  },
  {
    "id": "enbyasian",
    "entry": "npc-src/enbyasian.json"
  },
  {
    "id": "heroine",
    "entry": "npc-src/heroine.json"
  },
  {
    "id": "invisible",
    "entry": "npc-src/invisible.json"
  },
  {
    "id": "npc.37707_female",
    "entry": "npc-src/npc.37707_female.json"
  },
  {
    "id": "npc.37707_female_missing",
    "entry": "npc-src/npc.37707_female_missing.json"
  },
  {
    "id": "npc.37707_male_missing",
    "entry": "npc-src/npc.37707_male_missing.json"
  },
  {
    "id": "npc.barmaid",
    "entry": "npc-src/npc.barmaid.json"
  },
  {
    "id": "npc.barmaid_blonde",
    "entry": "npc-src/npc.barmaid_blonde.json"
  },
  {
    "id": "npc.barmaid_red",
    "entry": "npc-src/npc.barmaid_red.json"
  },
  {
    "id": "npc.beachcomber",
    "entry": "npc-src/npc.beachcomber.json"
  },
  {
    "id": "npc.beachcomber_black",
    "entry": "npc-src/npc.beachcomber_black.json"
  },
  {
    "id": "npc.beachcomber_blue",
    "entry": "npc-src/npc.beachcomber_blue.json"
  },
  {
    "id": "npc.beachcomber_copper",
    "entry": "npc-src/npc.beachcomber_copper.json"
  },
  {
    "id": "npc.beachcomber_fiery",
    "entry": "npc-src/npc.beachcomber_fiery.json"
  },
  {
    "id": "npc.beachcomber_gray",
    "entry": "npc-src/npc.beachcomber_gray.json"
  },
  {
    "id": "npc.bob",
    "entry": "npc-src/npc.bob.json"
  },
  {
    "id": "npc.boss_orange",
    "entry": "npc-src/npc.boss_orange.json"
  },
  {
    "id": "npc.boss_red",
    "entry": "npc-src/npc.boss_red.json"
  },
  {
    "id": "npc.boulder",
    "entry": "npc-src/npc.boulder.json"
  },
  {
    "id": "npc.box",
    "entry": "npc-src/npc.box.json"
  },
  {
    "id": "npc.catgirl",
    "entry": "npc-src/npc.catgirl.json"
  },
  {
    "id": "npc.catgirl_blonde",
    "entry": "npc-src/npc.catgirl_blonde.json"
  },
  {
    "id": "npc.catgirl_blue",
    "entry": "npc-src/npc.catgirl_blue.json"
  },
  {
    "id": "npc.catgirl_fiery",
    "entry": "npc-src/npc.catgirl_fiery.json"
  },
  {
    "id": "npc.catgirl_green",
    "entry": "npc-src/npc.catgirl_green.json"
  },
  {
    "id": "npc.catgirl_violet",
    "entry": "npc-src/npc.catgirl_violet.json"
  },
  {
    "id": "npc.ceo",
    "entry": "npc-src/npc.ceo.json"
  },
  {
    "id": "npc.childactor",
    "entry": "npc-src/npc.childactor.json"
  },
  {
    "id": "npc.childactor_black",
    "entry": "npc-src/npc.childactor_black.json"
  },
  {
    "id": "npc.childactor_blonde",
    "entry": "npc-src/npc.childactor_blonde.json"
  },
  {
    "id": "npc.childactor_fiery",
    "entry": "npc-src/npc.childactor_fiery.json"
  },
  {
    "id": "npc.christie",
    "entry": "npc-src/npc.christie.json"
  },
  {
    "id": "npc.conileaf",
    "entry": "npc-src/npc.conileaf.json"
  },
  {
    "id": "npc.cooldude",
    "entry": "npc-src/npc.cooldude.json"
  },
  {
    "id": "npc.cooldude_black",
    "entry": "npc-src/npc.cooldude_black.json"
  },
  {
    "id": "npc.cooldude_blue",
    "entry": "npc-src/npc.cooldude_blue.json"
  },
  {
    "id": "npc.cooldude_fiery",
    "entry": "npc-src/npc.cooldude_fiery.json"
  },
  {
    "id": "npc.disciple",
    "entry": "npc-src/npc.disciple.json"
  },
  {
    "id": "npc.dragonrider",
    "entry": "npc-src/npc.dragonrider.json"
  },
  {
    "id": "npc.dragonrider_black",
    "entry": "npc-src/npc.dragonrider_black.json"
  },
  {
    "id": "npc.dragonrider_blue",
    "entry": "npc-src/npc.dragonrider_blue.json"
  },
  {
    "id": "npc.dragonrider_fiery",
    "entry": "npc-src/npc.dragonrider_fiery.json"
  },
  {
    "id": "npc.dragonrider_green",
    "entry": "npc-src/npc.dragonrider_green.json"
  },
  {
    "id": "npc.drokoro",
    "entry": "npc-src/npc.drokoro.json"
  },
  {
    "id": "npc.fashionista",
    "entry": "npc-src/npc.fashionista.json"
  },
  {
    "id": "npc.fashionista_fiery",
    "entry": "npc-src/npc.fashionista_fiery.json"
  },
  {
    "id": "npc.firefighter",
    "entry": "npc-src/npc.firefighter.json"
  },
  {
    "id": "npc.firenymph",
    "entry": "npc-src/npc.firenymph.json"
  },
  {
    "id": "npc.fisher",
    "entry": "npc-src/npc.fisher.json"
  },
  {
    "id": "npc.fisher_fiery",
    "entry": "npc-src/npc.fisher_fiery.json"
  },
  {
    "id": "npc.florist",
    "entry": "npc-src/npc.florist.json"
  },
  {
    "id": "npc.florist_black",
    "entry": "npc-src/npc.florist_black.json"
  },
  {
    "id": "npc.florist_blue",
    "entry": "npc-src/npc.florist_blue.json"
  },
  {
    "id": "npc.florist_brown",
    "entry": "npc-src/npc.florist_brown.json"
  },
  {
    "id": "npc.florist_fiery",
    "entry": "npc-src/npc.florist_fiery.json"
  },
  {
    "id": "npc.florist_rose",
    "entry": "npc-src/npc.florist_rose.json"
  },
  {
    "id": "npc.girl1",
    "entry": "npc-src/npc.girl1.json"
  },
  {
    "id": "npc.goth",
    "entry": "npc-src/npc.goth.json"
  },
  {
    "id": "npc.granny",
    "entry": "npc-src/npc.granny.json"
  },
  {
    "id": "npc.granny_green",
    "entry": "npc-src/npc.granny_green.json"
  },
  {
    "id": "npc.granny_lapi",
    "entry": "npc-src/npc.granny_lapi.json"
  },
  {
    "id": "npc.granny_yellow",
    "entry": "npc-src/npc.granny_yellow.json"
  },
  {
    "id": "npc.heroine",
    "entry": "npc-src/npc.heroine.json"
  },
  {
    "id": "npc.heroine_brown",
    "entry": "npc-src/npc.heroine_brown.json"
  },
  {
    "id": "npc.heroine_red",
    "entry": "npc-src/npc.heroine_red.json"
  },
  {
    "id": "npc.homemaker",
    "entry": "npc-src/npc.homemaker.json"
  },
  {
    "id": "npc.homemaker_black",
    "entry": "npc-src/npc.homemaker_black.json"
  },
  {
    "id": "npc.homemaker_blonde",
    "entry": "npc-src/npc.homemaker_blonde.json"
  },
  {
    "id": "npc.homemaker_fiery",
    "entry": "npc-src/npc.homemaker_fiery.json"
  },
  {
    "id": "npc.knight",
    "entry": "npc-src/npc.knight.json"
  },
  {
    "id": "npc.knight_green",
    "entry": "npc-src/npc.knight_green.json"
  },
  {
    "id": "npc.knight_red",
    "entry": "npc-src/npc.knight_red.json"
  },
  {
    "id": "npc.knight_yellow",
    "entry": "npc-src/npc.knight_yellow.json"
  },
  {
    "id": "npc.knightlord",
    "entry": "npc-src/npc.knightlord.json"
  },
  {
    "id": "npc.landrace",
    "entry": "npc-src/npc.landrace.json"
  },
  {
    "id": "npc.magician",
    "entry": "npc-src/npc.magician.json"
  },
  {
    "id": "npc.magician_black",
    "entry": "npc-src/npc.magician_black.json"
  },
  {
    "id": "npc.magician_blonde",
    "entry": "npc-src/npc.magician_blonde.json"
  },
  {
    "id": "npc.magician_brown",
    "entry": "npc-src/npc.magician_brown.json"
  },
  {
    "id": "npc.magician_fiery",
    "entry": "npc-src/npc.magician_fiery.json"
  },
  {
    "id": "npc.magician_grey",
    "entry": "npc-src/npc.magician_grey.json"
  },
  {
    "id": "npc.maniac",
    "entry": "npc-src/npc.maniac.json"
  },
  {
    "id": "npc.maniac_green",
    "entry": "npc-src/npc.maniac_green.json"
  },
  {
    "id": "npc.maniac_rose",
    "entry": "npc-src/npc.maniac_rose.json"
  },
  {
    "id": "npc.maniac_violet",
    "entry": "npc-src/npc.maniac_violet.json"
  },
  {
    "id": "npc.maniac_yellow",
    "entry": "npc-src/npc.maniac_yellow.json"
  },
  {
    "id": "npc.miner",
    "entry": "npc-src/npc.miner.json"
  },
  {
    "id": "npc.miner_blue",
    "entry": "npc-src/npc.miner_blue.json"
  },
  {
    "id": "npc.miner_green",
    "entry": "npc-src/npc.miner_green.json"
  },
  {
    "id": "npc.miner_red",
    "entry": "npc-src/npc.miner_red.json"
  },
  {
    "id": "npc.miner_yellow",
    "entry": "npc-src/npc.miner_yellow.json"
  },
  {
    "id": "npc.missing",
    "entry": "npc-src/npc.missing.json"
  },
  {
    "id": "npc.monk",
    "entry": "npc-src/npc.monk.json"
  },
  {
    "id": "npc.monk_black",
    "entry": "npc-src/npc.monk_black.json"
  },
  {
    "id": "npc.monk_blue",
    "entry": "npc-src/npc.monk_blue.json"
  },
  {
    "id": "npc.monk_green",
    "entry": "npc-src/npc.monk_green.json"
  },
  {
    "id": "npc.monk_orange",
    "entry": "npc-src/npc.monk_orange.json"
  },
  {
    "id": "npc.monk_red",
    "entry": "npc-src/npc.monk_red.json"
  },
  {
    "id": "npc.ninja",
    "entry": "npc-src/npc.ninja.json"
  },
  {
    "id": "npc.ninja_blue",
    "entry": "npc-src/npc.ninja_blue.json"
  },
  {
    "id": "npc.ninja_red",
    "entry": "npc-src/npc.ninja_red.json"
  },
  {
    "id": "npc.nurse",
    "entry": "npc-src/npc.nurse.json"
  },
  {
    "id": "npc.nurse_blonde",
    "entry": "npc-src/npc.nurse_blonde.json"
  },
  {
    "id": "npc.nurse_blue",
    "entry": "npc-src/npc.nurse_blue.json"
  },
  {
    "id": "npc.nurse_green",
    "entry": "npc-src/npc.nurse_green.json"
  },
  {
    "id": "npc.nurse_lapi",
    "entry": "npc-src/npc.nurse_lapi.json"
  },
  {
    "id": "npc.nurse_red",
    "entry": "npc-src/npc.nurse_red.json"
  },
  {
    "id": "npc.omnichannelallie",
    "entry": "npc-src/npc.omnichannelallie.json"
  },
  {
    "id": "npc.overseer",
    "entry": "npc-src/npc.overseer.json"
  },
  {
    "id": "npc.p_five",
    "entry": "npc-src/npc.p_five.json"
  },
  {
    "id": "npc.p_four",
    "entry": "npc-src/npc.p_four.json"
  },
  {
    "id": "npc.p_one",
    "entry": "npc-src/npc.p_one.json"
  },
  {
    "id": "npc.p_three",
    "entry": "npc-src/npc.p_three.json"
  },
  {
    "id": "npc.p_two",
    "entry": "npc-src/npc.p_two.json"
  },
  {
    "id": "npc.picnicker",
    "entry": "npc-src/npc.picnicker.json"
  },
  {
    "id": "npc.postboy",
    "entry": "npc-src/npc.postboy.json"
  },
  {
    "id": "npc.postboy_green",
    "entry": "npc-src/npc.postboy_green.json"
  },
  {
    "id": "npc.postboy_red",
    "entry": "npc-src/npc.postboy_red.json"
  },
  {
    "id": "npc.professor",
    "entry": "npc-src/npc.professor.json"
  },
  {
    "id": "npc.professor_black",
    "entry": "npc-src/npc.professor_black.json"
  },
  {
    "id": "npc.professor_blue",
    "entry": "npc-src/npc.professor_blue.json"
  },
  {
    "id": "npc.professor_brown",
    "entry": "npc-src/npc.professor_brown.json"
  },
  {
    "id": "npc.professor_fiery",
    "entry": "npc-src/npc.professor_fiery.json"
  },
  {
    "id": "npc.professor_green",
    "entry": "npc-src/npc.professor_green.json"
  },
  {
    "id": "npc.professor_lapi",
    "entry": "npc-src/npc.professor_lapi.json"
  },
  {
    "id": "npc.riverboatcaptain",
    "entry": "npc-src/npc.riverboatcaptain.json"
  },
  {
    "id": "npc.robot",
    "entry": "npc-src/npc.robot.json"
  },
  {
    "id": "npc.rockitten",
    "entry": "npc-src/npc.rockitten.json"
  },
  {
    "id": "npc.rogue",
    "entry": "npc-src/npc.rogue.json"
  },
  {
    "id": "npc.rogue_copper",
    "entry": "npc-src/npc.rogue_copper.json"
  },
  {
    "id": "npc.rogue_green",
    "entry": "npc-src/npc.rogue_green.json"
  },
  {
    "id": "npc.rogue_red",
    "entry": "npc-src/npc.rogue_red.json"
  },
  {
    "id": "npc.scientist",
    "entry": "npc-src/npc.scientist.json"
  },
  {
    "id": "npc.scientist_black",
    "entry": "npc-src/npc.scientist_black.json"
  },
  {
    "id": "npc.scientist_brown",
    "entry": "npc-src/npc.scientist_brown.json"
  },
  {
    "id": "npc.scientist_fiery",
    "entry": "npc-src/npc.scientist_fiery.json"
  },
  {
    "id": "npc.screen",
    "entry": "npc-src/npc.screen.json"
  },
  {
    "id": "npc.screen_small",
    "entry": "npc-src/npc.screen_small.json"
  },
  {
    "id": "npc.shopassistant",
    "entry": "npc-src/npc.shopassistant.json"
  },
  {
    "id": "npc.shopassistant_black",
    "entry": "npc-src/npc.shopassistant_black.json"
  },
  {
    "id": "npc.shopassistant_grey",
    "entry": "npc-src/npc.shopassistant_grey.json"
  },
  {
    "id": "npc.shopassistant_red",
    "entry": "npc-src/npc.shopassistant_red.json"
  },
  {
    "id": "npc.shopkeeper",
    "entry": "npc-src/npc.shopkeeper.json"
  },
  {
    "id": "npc.shopkeeper_blonde",
    "entry": "npc-src/npc.shopkeeper_blonde.json"
  },
  {
    "id": "npc.shopkeeper_brown",
    "entry": "npc-src/npc.shopkeeper_brown.json"
  },
  {
    "id": "npc.sign",
    "entry": "npc-src/npc.sign.json"
  },
  {
    "id": "npc.snugglepot",
    "entry": "npc-src/npc.snugglepot.json"
  },
  {
    "id": "npc.soldier",
    "entry": "npc-src/npc.soldier.json"
  },
  {
    "id": "npc.spyderboss",
    "entry": "npc-src/npc.spyderboss.json"
  },
  {
    "id": "npc.spyderboss_blonde",
    "entry": "npc-src/npc.spyderboss_blonde.json"
  },
  {
    "id": "npc.spyderboss_fiery",
    "entry": "npc-src/npc.spyderboss_fiery.json"
  },
  {
    "id": "npc.spyderboss_green",
    "entry": "npc-src/npc.spyderboss_green.json"
  },
  {
    "id": "npc.spyderboss_lapi",
    "entry": "npc-src/npc.spyderboss_lapi.json"
  },
  {
    "id": "npc.spyderrookie",
    "entry": "npc-src/npc.spyderrookie.json"
  },
  {
    "id": "npc.statue_blue",
    "entry": "npc-src/npc.statue_blue.json"
  },
  {
    "id": "npc.statue_green",
    "entry": "npc-src/npc.statue_green.json"
  },
  {
    "id": "npc.statue_grey",
    "entry": "npc-src/npc.statue_grey.json"
  },
  {
    "id": "npc.statue_orange",
    "entry": "npc-src/npc.statue_orange.json"
  },
  {
    "id": "npc.statue_orange_tipped",
    "entry": "npc-src/npc.statue_orange_tipped.json"
  },
  {
    "id": "npc.statue_red",
    "entry": "npc-src/npc.statue_red.json"
  },
  {
    "id": "npc.swimmer",
    "entry": "npc-src/npc.swimmer.json"
  },
  {
    "id": "npc.swimmer_blue",
    "entry": "npc-src/npc.swimmer_blue.json"
  },
  {
    "id": "npc.swimmer_green",
    "entry": "npc-src/npc.swimmer_green.json"
  },
  {
    "id": "npc.swimmer_orange",
    "entry": "npc-src/npc.swimmer_orange.json"
  },
  {
    "id": "npc.swimmer_red",
    "entry": "npc-src/npc.swimmer_red.json"
  },
  {
    "id": "npc.tennisplayer",
    "entry": "npc-src/npc.tennisplayer.json"
  },
  {
    "id": "npc.tennisplayer_fiery",
    "entry": "npc-src/npc.tennisplayer_fiery.json"
  },
  {
    "id": "npc.tennisplayer_green",
    "entry": "npc-src/npc.tennisplayer_green.json"
  },
  {
    "id": "npc.tennisplayer_lapi",
    "entry": "npc-src/npc.tennisplayer_lapi.json"
  },
  {
    "id": "npc.tuxeball_green",
    "entry": "npc-src/npc.tuxeball_green.json"
  },
  {
    "id": "npc.tuxeball_red",
    "entry": "npc-src/npc.tuxeball_red.json"
  },
  {
    "id": "npc.tuxeball_yellow",
    "entry": "npc-src/npc.tuxeball_yellow.json"
  },
  {
    "id": "npc.varmint",
    "entry": "npc-src/npc.varmint.json"
  },
  {
    "id": "npc.volcoli",
    "entry": "npc-src/npc.volcoli.json"
  },
  {
    "id": "npc.warrior",
    "entry": "npc-src/npc.warrior.json"
  },
  {
    "id": "npc.water_jemuar",
    "entry": "npc-src/npc.water_jemuar.json"
  },
  {
    "id": "npc.woodnymph",
    "entry": "npc-src/npc.woodnymph.json"
  },
  {
    "id": "npc.xerogrunt",
    "entry": "npc-src/npc.xerogrunt.json"
  },
  {
    "id": "penguin",
    "entry": "npc-src/penguin.json"
  },
  {
    "id": "swimmer",
    "entry": "npc-src/swimmer.json"
  },
  {
    "id": "tux_monster_menu_budaye",
    "entry": "npc-src/tux_monster_menu_budaye.json"
  },
  {
    "id": "tux_monster_menu_dollfin",
    "entry": "npc-src/tux_monster_menu_dollfin.json"
  },
  {
    "id": "tux_monster_menu_fruitera",
    "entry": "npc-src/tux_monster_menu_fruitera.json"
  },
  {
    "id": "tux_monster_menu_grintot",
    "entry": "npc-src/tux_monster_menu_grintot.json"
  },
  {
    "id": "tux_monster_menu_hydrone",
    "entry": "npc-src/tux_monster_menu_hydrone.json"
  },
  {
    "id": "tux_monster_menu_ignibus",
    "entry": "npc-src/tux_monster_menu_ignibus.json"
  },
  {
    "id": "tux_monster_menu_memnomnom",
    "entry": "npc-src/tux_monster_menu_memnomnom.json"
  },
  {
    "id": "tux_monster_menu_rockitten",
    "entry": "npc-src/tux_monster_menu_rockitten.json"
  }
] as const;

export const GAME_ASSETS: Omit<GameAssets, "npcSrc" | "animated" | "stream"> = {
  ground: {},
  upper: {},
  chunkColumns: {},
  maxChunks: 1,
  maxActors: 292,
  world: TERRAIN_WORLD,
  order: TERRAIN_ORDER,
  player: PLAYER,
  playerHeight: 32,
  anims: {
  "tux_bubble_exclamation": {
    "frames": [
      "assets/map-animations/tux_bubble_exclamation-0.png"
    ],
    "w": 16,
    "h": 16
  },
  "tux_dragonbirth_100000us": {
    "frames": [
      "assets/map-animations/tux_dragonbirth_100000us-0.png",
      "assets/map-animations/tux_dragonbirth_100000us-1.png",
      "assets/map-animations/tux_dragonbirth_100000us-2.png",
      "assets/map-animations/tux_dragonbirth_100000us-3.png",
      "assets/map-animations/tux_dragonbirth_100000us-4.png",
      "assets/map-animations/tux_dragonbirth_100000us-5.png",
      "assets/map-animations/tux_dragonbirth_100000us-6.png",
      "assets/map-animations/tux_dragonbirth_100000us-7.png",
      "assets/map-animations/tux_dragonbirth_100000us-8.png",
      "assets/map-animations/tux_dragonbirth_100000us-9.png",
      "assets/map-animations/tux_dragonbirth_100000us-10.png",
      "assets/map-animations/tux_dragonbirth_100000us-11.png",
      "assets/map-animations/tux_dragonbirth_100000us-12.png",
      "assets/map-animations/tux_dragonbirth_100000us-13.png",
      "assets/map-animations/tux_dragonbirth_100000us-14.png",
      "assets/map-animations/tux_dragonbirth_100000us-15.png",
      "assets/map-animations/tux_dragonbirth_100000us-16.png",
      "assets/map-animations/tux_dragonbirth_100000us-17.png",
      "assets/map-animations/tux_dragonbirth_100000us-18.png",
      "assets/map-animations/tux_dragonbirth_100000us-19.png",
      "assets/map-animations/tux_dragonbirth_100000us-20.png",
      "assets/map-animations/tux_dragonbirth_100000us-21.png",
      "assets/map-animations/tux_dragonbirth_100000us-22.png",
      "assets/map-animations/tux_dragonbirth_100000us-23.png",
      "assets/map-animations/tux_dragonbirth_100000us-24.png",
      "assets/map-animations/tux_dragonbirth_100000us-25.png",
      "assets/map-animations/tux_dragonbirth_100000us-26.png",
      "assets/map-animations/tux_dragonbirth_100000us-27.png",
      "assets/map-animations/tux_dragonbirth_100000us-28.png",
      "assets/map-animations/tux_dragonbirth_100000us-29.png",
      "assets/map-animations/tux_dragonbirth_100000us-30.png",
      "assets/map-animations/tux_dragonbirth_100000us-31.png",
      "assets/map-animations/tux_dragonbirth_100000us-32.png",
      "assets/map-animations/tux_dragonbirth_100000us-33.png",
      "assets/map-animations/tux_dragonbirth_100000us-34.png",
      "assets/map-animations/tux_dragonbirth_100000us-35.png",
      "assets/map-animations/tux_dragonbirth_100000us-36.png",
      "assets/map-animations/tux_dragonbirth_100000us-37.png",
      "assets/map-animations/tux_dragonbirth_100000us-38.png",
      "assets/map-animations/tux_dragonbirth_100000us-39.png",
      "assets/map-animations/tux_dragonbirth_100000us-40.png",
      "assets/map-animations/tux_dragonbirth_100000us-41.png",
      "assets/map-animations/tux_dragonbirth_100000us-42.png",
      "assets/map-animations/tux_dragonbirth_100000us-43.png",
      "assets/map-animations/tux_dragonbirth_100000us-44.png",
      "assets/map-animations/tux_dragonbirth_100000us-45.png",
      "assets/map-animations/tux_dragonbirth_100000us-46.png",
      "assets/map-animations/tux_dragonbirth_100000us-47.png",
      "assets/map-animations/tux_dragonbirth_100000us-48.png",
      "assets/map-animations/tux_dragonbirth_100000us-49.png",
      "assets/map-animations/tux_dragonbirth_100000us-50.png",
      "assets/map-animations/tux_dragonbirth_100000us-51.png",
      "assets/map-animations/tux_dragonbirth_100000us-52.png",
      "assets/map-animations/tux_dragonbirth_100000us-53.png",
      "assets/map-animations/tux_dragonbirth_100000us-54.png",
      "assets/map-animations/tux_dragonbirth_100000us-55.png",
      "assets/map-animations/tux_dragonbirth_100000us-56.png",
      "assets/map-animations/tux_dragonbirth_100000us-57.png",
      "assets/map-animations/tux_dragonbirth_100000us-58.png",
      "assets/map-animations/tux_dragonbirth_100000us-59.png"
    ],
    "w": 48,
    "h": 64
  },
  "tux_grass_100000us": {
    "frames": [
      "assets/map-animations/tux_grass_100000us-0.png",
      "assets/map-animations/tux_grass_100000us-1.png"
    ],
    "w": 16,
    "h": 16
  },
  "tux_grass_blue_100000us": {
    "frames": [
      "assets/map-animations/tux_grass_blue_100000us-0.png",
      "assets/map-animations/tux_grass_blue_100000us-1.png"
    ],
    "w": 16,
    "h": 16
  },
  "tux_grass_red_100000us": {
    "frames": [
      "assets/map-animations/tux_grass_red_100000us-0.png",
      "assets/map-animations/tux_grass_red_100000us-1.png"
    ],
    "w": 16,
    "h": 16
  }
},
  layers: {
  "tux_backdrop": {
    "placement": "screen",
    "variants": {
      "bg_gradient_blue": {
        "image": "assets/screen-layers/tux-backdrop-bg_gradient_blue.png"
      },
      "bg_gradient_blue_aeble_character": {
        "image": "assets/screen-layers/tux-backdrop-bg_gradient_blue_aeble_character.png"
      },
      "bg_gradient_blue_budaye_monster": {},
      "bg_gradient_blue_dollfin_monster": {},
      "bg_gradient_blue_grintot_monster": {},
      "bg_gradient_blue_ignibus_monster": {},
      "bg_gradient_blue_memnomnom_monster": {},
      "bg_gradient_blue_rockitten_monster": {},
      "bg_gradient_blue_spyder_monsters_image": {
        "image": "assets/screen-layers/tux-backdrop-bg_gradient_blue_spyder_monsters_image.png"
      },
      "bg_gradient_blue_spyder_morph_image": {
        "image": "assets/screen-layers/tux-backdrop-bg_gradient_blue_spyder_morph_image.png"
      },
      "bg_gradient_blue_spyder_omnichannel_beaverbrook_character": {
        "image": "assets/screen-layers/tux-backdrop-bg_gradient_blue_spyder_omnichannel_beaverbrook_character.png"
      },
      "bg_gradient_blue_spyder_tumble_image": {
        "image": "assets/screen-layers/tux-backdrop-bg_gradient_blue_spyder_tumble_image.png"
      }
    }
  },
  "tux_overlay": {
    "placement": "screen",
    "defaultVisible": false,
    "variants": {
      "color_0_0_0_255": {
        "color": "#000000ff"
      },
      "color_0_0_128_128": {
        "color": "#00008080"
      },
      "color_102_51_0_128": {
        "color": "#66330080"
      },
      "image_gfx_ui_overlay_torchlight_png": {
        "image": "assets/screen-layers/tux-overlay-image_gfx_ui_overlay_torchlight_png.png"
      }
    }
  }
},
};
