// AUTO-GENERATED by gen-assets.ts — do not edit.
// Lazy monster-intro backdrops: variant -> on-demand IMG entry. The texture
// is uploaded only when the screen first shows the variant.
export const PORTRAIT_BACKDROPS: Readonly<Record<string, { entry: string; w: number; h: number }>> = {
  "bg_gradient_blue_budaye_monster": {
    "entry": "portraits/bg_gradient_blue_budaye_monster.img",
    "w": 256,
    "h": 256
  },
  "bg_gradient_blue_dollfin_monster": {
    "entry": "portraits/bg_gradient_blue_dollfin_monster.img",
    "w": 256,
    "h": 256
  },
  "bg_gradient_blue_grintot_monster": {
    "entry": "portraits/bg_gradient_blue_grintot_monster.img",
    "w": 256,
    "h": 256
  },
  "bg_gradient_blue_ignibus_monster": {
    "entry": "portraits/bg_gradient_blue_ignibus_monster.img",
    "w": 256,
    "h": 256
  },
  "bg_gradient_blue_memnomnom_monster": {
    "entry": "portraits/bg_gradient_blue_memnomnom_monster.img",
    "w": 256,
    "h": 256
  },
  "bg_gradient_blue_rockitten_monster": {
    "entry": "portraits/bg_gradient_blue_rockitten_monster.img",
    "w": 256,
    "h": 256
  }
};
